### ISSUE TITLE
January 2015 meet up

### ISSUE THREAD

**Issue by gausby** [cphex/cphex#11]
CphEx meet up, January 2015

Date: January 20, 2015 @ 19h
Location: Prototype; Haderslevgade 24; Copenhagen; Denmark

* * *

Let us coordinate the January 2015 meet up.

<strike>I suggest that we do the meet up at Prototype the 19th or 20th.</strike>

<strike>I will contact Prototype and try to make sure it will be open on the evening we decide on.</strike>

**Comment by gausby** [comment]
The meeting will take place at Prototype

    Prototype; Haderslevgade 24; Copenhagen; Denmark

I've updated the issue.

**Comment by gausby** [comment]
Thanks for a great meet up. See you in February (if not before) https://github.com/cphex/cphex/issues/14

**Comment by oscarfelipe** [comment]
:), Thank you guys and see you on the next one!
