### ISSUE TITLE
Team Elixir at Node.js Hackathon #8 (open data edition)

### ISSUE THREAD

**Issue by gausby** [cphex/cphex#12]
There will be a Node Hackathon somewhere, Saturday, January 10th.

  * http://www.meetup.com/Copenhagen-Node-js-Hackathon/events/219295140/

I have asked Mathias and he assured me that nobody will get a beating for hacking something else than Node.js—I will most likely be there, and my Emacs will be set to elixir-mode.

**Comment by madscoaducom** [comment]
Great idea.

I would like to join as well. I have another event starting at the same
time, but once done I will contact you and see if you are still there.
