### ISSUE TITLE
March 2015 meet up

### ISSUE THREAD

**Issue by gausby** [cphex/cphex#15]
**Copenhagen Elixir March 2015 meet up**

Date: March 10
Time: 18h
Location: Umwelt A/S

> Umwelt A/S
> Kristen Bernikows Gade 6
> 1105 København K, Denmark

Program:
  * TBA

Sign up here: http://lanyrd.com/2015/cphex/

* * *

Let's organise a meet up for March 2015. <strike>I am going to the US March 16th, so I suggest that we have the meeting Thursday, March 12 at 19h.</strike>

**Comment by oscarfelipe** [comment]
:+1: what about at 18:00, same day?

**Comment by gausby** [comment]
18h would work for me too.

**Comment by emilbayes** [comment]
I'd love to join you for this one!

**Comment by gausby** [comment]
@emilbayes you are invited. Also remember our meet up this Tuesday at eTilbudsavisen.

**Comment by madsflensted** [comment]
Great meetup at eTilbudsavisen. I'd hate miss the March one, but Thursdays don't work for me. Any chance we can move it to Monday or Tuesday in the same week?

**Comment by gausby** [comment]
Manday and Tuesday would work for me. The only day I have something I can't move is Wednesday.

**Comment by oscarfelipe** [comment]
I can make it both Monday or Tuesday

**Comment by ahf** [comment]
Hey guys,

Thanks for a great meet-up! eTilbudsavis will happily host another meet-up as long as you guys can come up with a date for us - I will check that we don't have anything else that evening once we know when :-)

**Comment by skovsgaard** [comment]
I'm up for either the 12th or the Tuesday of that week.

Is Tuesday better for everyone or should we stick to to Thursday the 12th?

**Comment by madsflensted** [comment]
Then it sounds like we should go for Tuesday (March 10.)

@ahf is that evening availabe at eTilbudsavisen?

**Comment by gausby** [comment]
I've updated the issue. I can book a meeting room at my office if eTilbudsavisen should be unavailable March 10.

**Comment by emilbayes** [comment]
If we need space I'm sure we can use our office at Umwelt as well. They're quite easy to get to (~200m from Kgs. Nytorv, ~700m from Nørreport)

**Comment by ahf** [comment]
The 10th is fine for us.

**Comment by gausby** [comment]
Umwelt might have a better location when it comes to transportation, but I really liked the setup at eTilbudsavis.

```iex
Interactive Elixir (1.0.3) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> << a :: 32, b :: 32, c :: 32 >> = :crypto.rand_bytes(12)
<<209, 237, 223, 203, 54, 17, 21, 6, 47, 111, 126, 21>>
iex(2)> :random.seed(a,b,c)
:undefined
iex(3)> :random.seed(a,b,c)
{12720, 273, 4714}
iex(4)> if :random.uniform > 0.5, do: "Umwelt", else: "eTilbudsavis"
"eTilbudsavis"
```

I have been playing with Ports. I might be able to give a talk about them.

**Comment by ahf** [comment]
I'd like to talk about doing a meet-up page or something to reach out to more people, if that has an interest. I'll happily sponsor it too as long as we reach out as broad as we did last time: a mixture of Erlang and Elixir people :-P

**Comment by ahf** [comment]
Oh, and I also think it's healthy that we have more than one venue to rotate between :-) Very nice!

**Comment by gausby** [comment]
Okay, I'll put Umwelt as the location. @emilbayes what's the address?

I don't know about meetup.com. My feeling is that discoverability is minimal as their business model is group creation, and Funktionelle Københavnere has a ton of members but only a handful show up to their events.

We should do more about marketing, but I think meetup.com is a dud.

**Comment by ahf** [comment]
MF#K have, like many user groups, lots of participants when they announce presentations :-)

Another option is http://lanyrd.com which as far as I know is free.

**Comment by gausby** [comment]
Let's try Lanyrd for organising this event: http://lanyrd.com/2015/cphex/

**Comment by emilbayes** [comment]
Great! The address is:

Umwelt A/S
Kristen Bernikows Gade 6
1105 København K

What do we need? I guess projector and adapters. HDMI? DisplayPort?
How many people attended last time?

**Comment by gausby** [comment]
Thanks. I've added the address to the issue.

Yes, a projector and different adapters. Personally I would need a DisplayPort but the attendants are mostly on PC's.

8 people was present at the last meet up.

**Comment by oscarfelipe** [comment]
Great there are so many great companies that are willing to host the meetup!, .

I remember that one of the founders  of the Clojure meetup here in Cph mentioned once that they got a more broad exposition when one of the members opened a meetup account for the group. I found the group in deed through the meetup site, just as I found the funktionelle københavner meetup back in november 2013. Therefore it is also my impression that there is some kind of good logistic behind the application that attracts the right person to the right group. I don't know, I like the meetup website :/

As Erlang developer I also like the idea of a broader meetup, and since we are so few Elixir participants and the topics are so relevant to each other, make sense to me to participate in the same group.

**Comment by skovsgaard** [comment]
I may have to cancel for Tuesday, being busy wrapping up a school project.

**Comment by gausby** [comment]
@skovsgaard It's okay; Good luck with your school project and see you at one of the other meet ups!

**Comment by gausby** [comment]
I've tweeted out the meeting information for tonight, please retweet during the day (after noonish) to spread the message as much as possible: https://twitter.com/cph_ex/status/575228372931969024

**Comment by ahf** [comment]
I'll miss the meeting tonight as well - have a project at work where I got a few days delayed last week that I'd like to catch up on.

Have fun though, and see you guys at the next meeting :-)

**Comment by jlouis** [comment]
I'll drop by, for the heck of it :) I assume you can just walk in through the door or call appropriately on a button.

**Comment by emilbayes** [comment]
Yep! 1st floor. It says "Umwelt Technical". Otherwise give me a call on +45 42 955 144

**Comment by gausby** [comment]
Thanks for a great meet up, see you at the April meet up #16

**Comment by madsflensted** [comment]
I have created a [cphex team](http://exercism.io/teams/cphex) on http://exercism.io, 
I don't know what you can do with teams yet, but if you want to join the team just ping me your exercism username and I will add you.

**Comment by emilbayes** [comment]
@madsflensted I clicked the link but am met with the message: 
> You may only view team pages for teams that you are a member of, or that you manage.

My username is emilbayes

**Comment by madsflensted** [comment]
@emilbayes I have added you to the group (as manager so you can add others as well).

**Comment by gausby** [comment]
@madsflensted could you add me as well? I guess my username is @gausby

We could update the README.md file of this github repo to include links to stuff like exercism.io.

**Comment by gausby** [comment]
And the links from the discussion about Ports:

  * https://github.com/alco/porcelain
  * https://github.com/saleyn/erlexec

* * *

This is the link to the hashing library that implements NIF's with dirty schedulers by @jlouis: https://github.com/jlouis/enacl

Besides that we talked about [QuickCheck](http://quviq.com). We looked at the Quickcheck models in the eNaCL and [Poolboy](https://github.com/devinus/poolboy/blob/master/test/poolboy_eqc.erl) project

**Comment by madsflensted** [comment]
@gausby added you as well

**Comment by madsflensted** [comment]
and updated the README.md with links

**Comment by gausby** [comment]
:+1:

**Comment by ahf** [comment]
Any date for next meet-up? 

I can talk about `riak_core` if someone have an interest in that, but I do need a few weeks to prepare unless it's going to be all live coding :-)

**Comment by madsflensted** [comment]
@ahf next date options are over on #16
