### ISSUE TITLE
April 2015 meet up 

### ISSUE THREAD

**Issue by gausby** [cphex/cphex#16]
Copenhagen Elixir April Meetup

Date: April 29
Time: 18:00
Location: Umwelt A/S

> Umwelt A/S
> Kristen Bernikows Gade 6
> 1105 København K, Denmark

Agenda: 

* Talks
  - Live coding event by @gausby
  - A small streaming demo by @madsflensted 
* Talk about upcoming Copenhagen Elixir events
  - May meet up
  - Hardware hacking event
* Random talk about Elixir

Umwelt will provide snacks, but there will not be food at this event. Be sure to grab something before the event :)

*See you all at Umwelt, Wednesday at 18h*

* * *

<strike>Let's throw together a meet up for April 2015.</strike>

<strike>Please contact us if you <strike>want to host</strike>, have a talk, have an idea for a topic, and <strike>let's find a suiting date.</strike></strike>

<strike>Elixirconf Europe is on in week 17, so I suggest that we have our meeting the week after.</strike>

**Comment by madsflensted** [comment]
I would suggest that it could be wedensday April 29.
Or the following week May 4 - 6

**Comment by gausby** [comment]
I think that the April meet up should be in April, so my vote is on 29th

27, 28, 29 and 30 would work for me.

**Comment by oscarfelipe** [comment]
:+1:  29th of April

**Comment by gausby** [comment]
Okay; let's commit to 29th, any objections?

Now we need a location and perhaps some talks. Alex said he wanted to show riak-core, is still offer still valid?

**Comment by emilbayes** [comment]
We can always host, but we might want to alternate between venues :)

**Comment by gausby** [comment]
@emilbayes :+1: Let's keep the location needed label on in case someone else want to host then.

**Comment by gausby** [comment]
@emilbayes Alex will not be able to make it April 29, so let's have the meeting at Umwelt.

**Comment by gausby** [comment]
Anyone wanna see me live code a morse code encoder/decoder in Elixir?

It is not much, but it could be a fun "talk" and everyone could pitch in with ideas, etc.

**Comment by emilbayes** [comment]
@gausby Alright, I'll make reservations :)

**Comment by gausby** [comment]
@emilbayes cool, I've updated the location in the issue. I've also added a time.

Everyone: Is 18h alright?

**Comment by madsflensted** [comment]
Works for me

**Comment by madsflensted** [comment]
+1 for morse code live coding :-)

**Comment by oscarfelipe** [comment]
morse code live coding sounds great and 18:00 is fine :tram:

**Comment by skovsgaard** [comment]
A belated +1 from here. 18h sounds fine.

**Comment by gausby** [comment]
I've updated the issue with details about the meet up. See you all at Umwelt, Wednesday at 18h.

**Comment by gausby** [comment]
Thanks for a great meet up. See you in May! #18

**Comment by emilbayes** [comment]
@gausby You should add a link to your talk repo to the top of this issue for future reference :)

**Comment by gausby** [comment]
@emilbayes sure, this is the article I wrote for the presentation: [https://github.com/gausby/morse-code-presentation](https://github.com/gausby/morse-code-presentation)—it is work in progress but the general pointers are there!
