### ISSUE TITLE
Copenhagen Elixir May Meetup

### ISSUE THREAD

**Issue by gausby** [cphex/cphex#18]
**UPDATE** New location, and there is no need to register with GOTO. Please tell everyone about this.

Event
--------

Date: May 26
Time: 17.00 - 19.00

Location:
> e-conomic
> Langebrogade 1, building A
> 1411 Copenhagen K
> Denmark

Agenda
----------

* Talk:
  * Torben Hoffmann: “Building Lego Robots with Elixir”

Help spreading the word
---------------------------------

<strike>Please retweet the [announcement from our twitter account](https://twitter.com/cph_ex/status/595871734194184192) to your followers to create some noise about the event. It is going to be a good one.</strike>

Do make some noise about the event, but don't retweet the previously mentioned tweet as it points to the wrong venue.

* * *
Please comment on this issue if you want to add something.

**Comment by madsflensted** [comment]
Looking forward to this one, and I would prefer the 26th.

**Comment by gausby** [comment]
Yeah. I think I'll tell them that the meeting should be on the 26th. No one has voiced strong opinions here or elsewhere.

This is going to be good.

**Comment by gausby** [comment]
I've added a speaker to the issue. Still awaiting confirmation from the venue.

**Comment by oscarfelipe** [comment]
it seems like  the venue will be Borgergade 24 (1. sal), 1300 København K.
like the last year Torben's presentation about Erlang.

https://secure.trifork.com/cph-2015/freeevent/index.jsp?eventOID=7092
http://gotocon.com/cph-2015/upcomingevents/

**Comment by gausby** [comment]
@oscarfelipe Indeed it will.

Please retweet the announcement on twitter so that we can get the word out about the group. I'll update our meetup.com page (:-/) later.

  * https://twitter.com/cph_ex/status/595871734194184192

**Comment by emilbayes** [comment]
They've put it on meetup too: http://www.meetup.com/GOTO-Nights-Meetup/events/222350467/?a=fj1_mup

**Comment by gausby** [comment]
We just need to register on the GOTO page. I think this meetup.com stuff just adds confusion. :)

**Comment by gausby** [comment]
You don't need to register using the GOTO page any more.

We will carry on with the event, but GOTO are no longer part of the organisation. So we need a new venue. I can pull some strings, but ask around and please contact us if you have a venue suited for aprox 15 people.

**Comment by gausby** [comment]
E-conomic can host. I'll start communicating that.

**Comment by gausby** [comment]
Thanks for a great meet up, and thanks to @lehoff for giving a talk. See you all in June!
