### ISSUE TITLE
Extraordinary May get-together

### ISSUE THREAD

**Issue by madsflensted** [cphex/cphex#19]
At ElixirConfEU @gausby and I met @novaugust and now he is visiting Copenhagen on May 20th.
My idea is to arrange a get-together evening, were Matt can meet some Copenhagen Elixir people, get something to to eat and drink and talk about anything Elixir or otherwise. 

Place:  [Cafe Apropos](http://cafeapropos.dk/),
Time: Around six o'clock (18.00)

**Comment by novaugust** [comment]
Heyo, thanks Mads! Just to fill people in on me + Elixir, I came to the language with neither ruby nor erlang in my background and have been working with it full time since July of last year. I don't know that I have anything amazing to say about it, but that's more a reflection of me than the language :)

**Comment by oscarfelipe** [comment]
That sounds lovely :+1:

**Comment by gausby** [comment]
If we are going for food we should probably pick something danish/scandinavian—and if anyone is a vegan or vegetarian we should find a place with good vegan options as well.

We could perhaps do the get together at Prototype depending on how many we will be. Prototype is close to Kødbyen, which has some nice (but a tad pricy) restaurants.

**Comment by skovsgaard** [comment]
I'm in. What are the options time wise?

**Comment by madsflensted** [comment]
@gausby: I would suggest http://mother.dk, not danish but great pizza (with or without meat) and reassonably priced, and in "Kødbyen". Also has great atmosphere. We can always continue to one of the bars in the area if people are up for it.

 @novaugust would you be able to show off some real world Elixir? or should we just stick with the social part? (I am thinking do we need to meetup en a tech space first, or just go directly for food)

**Comment by gausby** [comment]
I've never been to mother, but I've heard good stuff. The reason I suggested Scandinavian food was mostly because of Matt who might have an interest in tasting something local.

**Comment by madsflensted** [comment]
yeah - just can't think of a place that is both good, affordable and Scandinavian ;-)
But ideas are welcome.

**Comment by gausby** [comment]
There's Cafe Samsø, but it far away from Prototype: http://www.nelso.com/dk/place/7970/

If we are going for something truly special we could go for a bøfsandwich with rødbeder and brunsovs at  Chicky Grill Bar http://www.tripadvisor.com/Restaurant_Review-g189541-d804851-Reviews-Chicky_Grill_Bar-Copenhagen_Zealand.html — a definite minus is the fact that people are allowed to smoke inside; but it is special.

**Comment by novaugust** [comment]
I'd be more than happy to give a presentation of what we're doing with elixir - sorry for the async, doing that rock climbing thing ;)

**Comment by gausby** [comment]
@novaugust cool. Would you need a projector?

**Comment by madsflensted** [comment]
Ok closing in on the 20th, I expect to update the issue tomorrow evening when @novaugust arrives in Cph, so stay tuned.

**Comment by madsflensted** [comment]
Ok @novaugust has landed. We have had a chat and Matt likes the idea of a social get together. So I propose that we meet at [Cafe Apropos](http://cafeapropos.dk/), which is just at the beggining of Sønder Boulevard, close to the main train station. From there we can easily reach the "Bøf sandwich" place that @gausby mentioned or any of the other places in Kødbyen when we feel like something to eat.

@oscarfelipe , @emilbayes, @skovsgaard - any of you able to join?.

I am updating the main issue with details

**Comment by gausby** [comment]
Yeah, I am still in! Should we broadcast this get together on the @cph_ex twitter account?

**Comment by madsflensted** [comment]
Yes absolutely, anybody who wants to show is welcome.

**Comment by novaugust** [comment]
I'll be there!
I think.
Probably?

**Comment by oscarfelipe** [comment]
:+1:  Hey Mads, I am looking forward to it, see you tomorrow at 18:00 at café apropos!

**Comment by novaugust** [comment]
Nahhh I'm in

**Comment by skovsgaard** [comment]
In case I forget the tweet: I'm sorry I'm kinda late on it, but I have to pass.

**Comment by emilbayes** [comment]
Unfortunately I have another meetup tonight :(

**Comment by madsflensted** [comment]
Thanks for turning up - we had a great evening chatting Elixir and life in general, and along the way we got introduced to a great bear place by @gausby. 
@novaugust : thanks for stopping by Copenhagen.

**Comment by gausby** [comment]
:+1: Good war stories. Thanks @novaugust !
