### ISSUE TITLE
Introduction to Protocols

### ISSUE THREAD

**Issue by gausby** [cphex/cphex#2]
It would be great with a talk about working with protocols in Elixir. Especially how to work with the Enumberable protocol in custom data structures.

About elixir protocols:
- http://elixir-lang.org/getting-started/protocols.html
- http://elixir-lang.org/docs/stable/elixir/Enumerable.html
- http://pminten.github.io/blog/2013/09/05/elixirs-enumerable/ <- a bit outdated

**Comment by skovsgaard** [comment]
If there's still a demand for this after a year, I've actually thought of doing a talk on it some time. Although what I'd rather do if we're going with more hands-on sessions from here on is try and create an exercise around the theme, protocols.

**Comment by gausby** [comment]
Great idea. Some problem that can be solved with a specific protocol would be a nice task for a hands-on-event.

I suggest that we still do talk evenings once in a while; I don't think they are a bad thing, we just need speakers. Actually I think the mob programming approach could be a mixture of the two; a person present the topic and then open an editor and everyone participate solving a problem on the projector.

**Comment by skovsgaard** [comment]
Absolutely. It's just a matter of planning it as mob programming. A regular talk would easily end up going way off track if mobbed, but something designed for it could work great.

I'm not really sure what'd be a good fit for it though.

**Comment by gausby** [comment]
It seems that validators are a really good fit for collectables.

I find that collectables a good if you have some recursive calling function that carries state around and just return that state when the computation is done. The exercise could be some refactor of one of these scenarios.

**Comment by skovsgaard** [comment]
I'm not sure I get it. Are we talking about extending parts `Collectable`?

**Comment by madscoaducom** [comment]
Good idea to to come up with challenge for our meetup. Can we fit it into
our Yatzy theme?

As for format, a15 min idea into could be a way?

Also if mob programming,  we should use the 5 min on keyboard rule

**Comment by gausby** [comment]
Actually the task and context could/should be explained with a presentation. I guess for a yatzy theme we need to present the game for the crowd who didn't grow up in a culture that play or know about yatzy.

@skovsgaard I'm am just talking about the protocol that I've been working the most with and have identified use-cases for.

**Comment by skovsgaard** [comment]
I wasn't saying it's a bad idea, given how it's everywhere. I just didn't get what you meant.

My initial thought was taking some feed (RSS or whatever) and defining a `Queryable` protocol for it. Or even better, extending Access to work on types like Feed or Entry (if we're talking RSS).

**Comment by gausby** [comment]
@skovsgaard Sorry; I was trying to air some ideas for what to do with protocol exercises.

**Comment by skovsgaard** [comment]
No, that's fine. My idea was just a thought too. It's not really the deciding factor whether we make exercises using existing ones or define new ones. I just couldn't think of any use cases that'd be doable in like a 15 minute session.

**Comment by gausby** [comment]
Should we just make this into an exercise for a meet up?

**Comment by skovsgaard** [comment]
That'd be pretty cool. Got any ideas for a protocol to implement? We could do the thing we did when we had the Enum tasks and simply take an existing protocol and implement it ourselves.

Alternatively it could be something like defining a few new types and extending a protocol to include them?

**Comment by gausby** [comment]
Well, I guess Collectable are good for validators: https://gist.github.com/gausby/da2a4a06ae68458fb91e

**Comment by skovsgaard** [comment]
I agree. I figured we'd either be looking at Colllectable or Enumerable if our exercise is extending an existing one, so very cool case to work from.

**Comment by madsflensted** [comment]
If you are unsettled on the topic, we could also give GraphQL a look?
Seems to be some good learning resources available for Elixir/Phoenix:

http://graphql-elixir.org/
http://absinthe-graphql.org/learning-graphql/

**Comment by gausby** [comment]
@madsflensted I really like the idea of GraphQL—I even use it in the product I am building right now—but I don't know how it relates to protocols?

**Comment by madsflensted** [comment]
My bad.  I meant to raise this on the subject for next meetup issue

**Comment by gausby** [comment]
No biggie. I like the idea, I was just confused.

**Comment by olleolleolle** [comment]
@gausby The URL to the Getting Started has changed to http://elixir-lang.org/getting-started/protocols.html

**Comment by gausby** [comment]
@olleolleolle thanks, I've updated the link. Perhaps I should do something about this issue and get it closed.

**Comment by gausby** [comment]
This is still a nice idea for a talk
