### ISSUE TITLE
Copenhagen Elixir June Meetup

### ISSUE THREAD

**Issue by gausby** [cphex/cphex#20]
*Date*:
Wedensay June 17. at 19.00

*Venue:*
BestBrains A/S
Sankt Gertruds Stræde 5, 3. sal
1129 København K
[Map](https://www.google.dk/maps/place/BestBrains+A%2FS/@55.683093,12.574061,17z/data=!4m6!1m3!3m2!1s0x465253123b6b7f17:0x5b471a65569599da!2sBestBrains+A%2FS!3m1!1s0x465253123b6b7f17:0x5b471a65569599da?hl=en)

*Talks:*
  * Elixir 101 (@skovsgaard) - if there are new people
  * Processes (@gausby)
  * Phoenix + Elm (@madsflensted)

**Comment by gausby** [comment]
I might give a talk on processes.

Should we pick the third monday or tuesday as the date?

**Comment by madscoaducom** [comment]
I am currently investigating possible venue. Will get feedback tomorrow.

Also planning a talk on Phoenix and Elm

**Comment by gausby** [comment]
:+1: awesome, Mads!

**Comment by madscoaducom** [comment]
Ok,  we have a location. I will finish the details during the weekend, and
update the issue

**Comment by madsflensted** [comment]
Ok Ihave updated the venue details. Some of my good friends at BestBrains have agreed to hosting this months meetup - and the location is great.

As for dates I suggest 
Monday June 15.
or
Wedensday June 17.

Any preferences?

**Comment by gausby** [comment]
Both days are okay with me, but I might prefer the Wednesday.

**Comment by skovsgaard** [comment]
Of the two, I think I'd prefer Wednesday too.

**Comment by gausby** [comment]
Okay; so, June 17th, at 19h?

**Comment by madscoaducom** [comment]
Fine with me.

**Comment by madsflensted** [comment]
As for talks, @gausby are you still up for talking about processes?

Also would anyone venture a "intro to elixir" talk? In case we have new comers

**Comment by gausby** [comment]
Yeah. 19h feels better than 17h.

Good job on finding a venue and thanks, @madsflensted :+1:

**Comment by gausby** [comment]
In regards to my talk: I'll try to sketch some stuff today and see if it can end up as a slide deck. I might give the presentation at Stockholm Elixir before EUC. It is still on :)

**Comment by oscarfelipe** [comment]
I have to deliver a project on Wednesday 19th of June. I cannot make it the 19th but I can offer the Introduction to Elixir and a talk about Erlang Finite State Machines  for July or August :)

**Comment by oscarfelipe** [comment]
sorry, I mean, the delivery is on Wednesday 17th, that is why I am not able to come that day

**Comment by madsflensted** [comment]
@oscarfelipe  sorry you can't make it - good luck with the project!

**Comment by skovsgaard** [comment]
I can so a short Elixir 101 if we have new people on the 17th.

**Comment by madsflensted** [comment]
Excellent!

**Comment by gausby** [comment]
Cool, I've added you to the talk roaster, @skovsgaard.

**Comment by madsflensted** [comment]
@gausby  are you comfortable confirming your talk? If you are I suggest we
update the issue and also list the talks on meetup.com, as Bestbrains may
notify their network about the event, and that could get us done visitors

**Comment by gausby** [comment]
I did some work on my talk yesterday, and I think it went pretty great; so yeah, I think I'll be ready, and it might even be good.

I will just have to coordinate with Jonas, as I am going into some basic Elixir 101 stuff.

**Comment by madscoaducom** [comment]
Awesome

**Comment by skovsgaard** [comment]
Just lemme know what you cover, and I will steer clear of it.

**Comment by gausby** [comment]
Everything between spawn and GenServer, I guess. You are free to mention them, I will try to go into great detail though :)

**Comment by madscoaducom** [comment]
This sounds great
Should we allocate some approx time for each talk?

**Comment by skovsgaard** [comment]
@gausby That's pretty much perfect. I was thinking of ignoring OTP entirely for my thing. I'm imagining pretty much an intro to the fundamentals, i.e. things that'd be different from an imperative language.

**Comment by madsflensted** [comment]
@gausby and @jsc so is it ok if we confirm both your talks in this description of this issue?

**Comment by gausby** [comment]
Yeah, I'll update the issue—I'll confirm my own talk.

**Comment by madsflensted** [comment]
@gausby and @jsc how much time do you think you will need? I thought I would aim for 45 min, what do you think?

**Comment by jsc** [comment]
I suspect you are looking for someone else. I am jsc, and I'm definitely
not in Denmark.

Cheers,

Shane

**Comment by madsflensted** [comment]
@jsc sorry about that

**Comment by gausby** [comment]
I am not that good at limiting myself; the last time I gave a presentation I droned on for 2 hours…I'll see if I can limit myself to 30 minutes.

**Comment by madscoaducom** [comment]
Ok lets aim for 30 min,  should it go longer, as in +15 min we will be fine.

**Comment by skovsgaard** [comment]
I can do mine in 15 minutes. I haven't prepared it yet, but I'll make it fit that. Especially if it's just touching on fundamentals of the language, really.

**Comment by chime-mu** [comment]
Hey Mads, really looking forward to your talk about Elixir and Elm as I'm looking at Elm as well.

**Comment by madsflensted** [comment]
@chime-mu that's great! I am having fun working on the demo.

**Comment by jugoncalves** [comment]
Elixir 101 +1
Phoenix + Elm +1

(I am new to Denmark and Elixir, it's going to be my first meetup here. ^_^)

**Comment by gausby** [comment]
@jugoncalves cool; Welcome, and I hope that you will enjoy my talk as well! :)

**Comment by jugoncalves** [comment]
@gausby I'm sure I'll enjoy it, although not sure whether I'll be able to follow it. :smile:

**Comment by skovsgaard** [comment]
Does anyone else with a talk mind if I open? I will have to defer some stuff (like processes) to the later talks, so it doesn't make sense if that's already covered.

**Comment by gausby** [comment]
@skovsgaard you can go first.

@madsflensted I just gave my talk at Stockholm Elixir, and I made it in around 25 minutes. Missed a few points I wanted to address, so I guess 30-35 minutes would do.

**Comment by madsflensted** [comment]
I think the order listed in the description gives a good flow

@gausby saw the pic and it looked like you where having fun.

**Comment by Reefersleep** [comment]
I'm new to Elixir, so I'd appreciate the 101 :) I know a bit of ruby, but I'm told that while the syntaxes looks deceptively similar, the semantics are *very* different.

**Comment by skovsgaard** [comment]
That is exactly what my talk will go into.

**Comment by Reefersleep** [comment]
How fortunate for me!

**Comment by ahf** [comment]
I'll join tonight as well.

**Comment by skovsgaard** [comment]
My presentation is up at github.com/skovsgaard/elixir101 (The html slides are in priv/static)

**Comment by madsflensted** [comment]
And the code for my Elm and Phoenix talk (with link to "slides") can be found at https://github.com/madsflensted/dots

**Comment by Reefersleep** [comment]
Cheers guys! Good job on the presentations! :+1:

**Comment by chime-mu** [comment]
Thanks a lot for your work with the presentations and for great evening :)

**Comment by gausby** [comment]
Thanks for coming out. We have had some good meetings through the times, but this one was definitely one of the best!

Let's have another meet up in July: #22
