### ISSUE TITLE
Remove link to Exercism on the front page

### ISSUE THREAD

**Issue by gausby** [cphex/cphex#21]
Are anyone using this? I've done some exercises and done some code review in there, but I haven't done it for a good while.

It would be a pity if someone went there and we didn't provide the service we promise on the front page.

Any thoughts?

**Comment by madsflensted** [comment]
Yeah - still think exercism.io is a good place for new comers to practice.
For now I have removed the part about the cphex group, as it is not active.

**Comment by gausby** [comment]
Cool. I am no copywriter but I kinda get a sense of "read this material, then you're on your own, kid" from the current wording.

We have to think a bit more about how to include new people to the community.
