### ISSUE TITLE
Copenhagen Elixir & Erlang meet up July 2015

### ISSUE THREAD

**Issue by gausby** [cphex/cphex#22]
Date: July 8, 2015 @ 18:00

> Arne Jacobsens Allé 16, 3.
> DK-2300 København S
> Danmark
>
> [Map](https://goo.gl/maps/GXS0K)

Talks
-----
* REST Web Services using Erlang/Cowboy by @oscarfelipe 
* Time and date demystified and how to handle it in Elixir by @lau 
* *You?*/*Lightning talks*?

* * *

N.b. We are a couple of attendees who are going to a food stand before the meet up. Be at the meet up location at 17:00 sharp if you want to join. Otherwise catch us on the @cph_ex twitter account.

**Comment by lukelex** [comment]
@gausby how many participants are expected?

**Comment by gausby** [comment]
@lukelex Hard to tell. Some might be on vacation and such, but at the meet up yesterday we had 14 people attending. I hope we will see the same number, and perhaps some newcomers, but again: vacation month :)

**Comment by lau** [comment]
I want to do a talk about: Time and date demystified and how to handle it in Elixir.

**Comment by gausby** [comment]
@lau :+1: I've added your talk to the roaster. Do you have a preference on what day it should be?

**Comment by oscarfelipe** [comment]
That sounds super good, 
I can give a talk about REST Web Services using Erlang/ Cowboy

**Comment by gausby** [comment]
Cool @oscarfelipe, I'll update the issue description when I get to a proper computer.

Should we line up a third talk, or is two enough?

**Comment by chime-mu** [comment]
Hey @lau - would it be relevant to include som information about the new date/time stuff in Erlang R18?

**Comment by lau** [comment]
Hi @chime-mu. Yes, I will probably say a few things about that too.

**Comment by gausby** [comment]
eTilbudsavis has offered to host the event on July 8.

Please add to the issue if you want to give a presentation about something or have suggestions that could make the event even better.

**Comment by gausby** [comment]
Thanks for a great meet up. A ton of new faces this time. Please give us feed back on what could be improved, and what you liked; and see you all in August!
