### ISSUE TITLE
Our meetup.com group is about to exceed the maximum amount of members

### ISSUE THREAD

**Issue by gausby** [cphex/cphex#23]
I just got the message on meetup.com that our group are about to exceed the maximum number of members for our current plan. Soon they will demand at least $5 per month to keep the group running.

I don't want to pay more than I already do. This group is non-profit, it will stay non-profit—and soon I will personally be without an income (to hack on Elixir all day, of course).

We need to find a solution to this. One solution could be to kick the obviouly fake members and keep kicking suspicious profiles (I suspect that they are planted by meetup.com to boost the number of members), or somebody else could fork over the what ever meetup.com demand every month.

I am really upset about this. As most of you know I have been against being on meetup.com since day one—because of shady behaviour like this—we are only there to be included on the official Elixir page.

One positive thing about this ordeal has been the growing number of members. It was really nice to see the great number of new faces at the last meet up. I do not know how many people found us because of meetup.com though; the Twitter announcements are broadcasted far and wide as well, and we were mentioned in a newsletter. Also, CPHFTW automatically add the group to their calendar via the meetup.com api. I cannot complain about that.

So:

  * anyone up for taking the bill?
  * any suggestions about what we should do about meetup.com?
  * There will be a rant about this at the next meet up

**Comment by madsflensted** [comment]
Suggestion:  at each meeting get everybody to "follow" or "watch" the github repo (actually go through the how-to during welcome part). Then ask the ones (usually new comers) that signed up via meetup group to leave the group. You update the description on meetup.com to include the number of github followers, e.g. "Don't be fooled, our group actually has NN members - go here to join in the community - link to github". (maybe there is an API for updating that description automatically?)
That way meetup.com expenses are kept low, and we direct the traffic where we want it, here on github.

**Comment by madsflensted** [comment]
just signed off the meetup.com group myself

**Comment by gausby** [comment]
Getting people to watch the repo is kinda a tall order—most people don't want the notifications every time somebody create an issue or comment. Getting people to *star* it should be easier :)

Would anyone be strongly opposed that I do a quick talk about my thoughts about how we organise the group, and the meetup.com situation at the next meet up? I promise to count to ten before my talk to get rid of most of the anger.

**Comment by gausby** [comment]
Also, I don't know if there are stuff to be gained from having a large amount of members when you are in the meetup.com ecosystem: Do "popular" groups rank higher than groups with fewer members?

**Comment by madsflensted** [comment]
hmm - maybe a idea for an elixir project, a "follow our github group" service that sits between github and the members, only sending them updates when a new meeting issue is created (maybe with some options)

**Comment by madsflensted** [comment]
If going all-in with meetup, there is this option (seen on their pricing page):
"You can share these costs with your members by using our Dues feature"

**Comment by gausby** [comment]
Sharing the costs is definitely way better than one person paying it all. Thanks for noticing that.

I will mention this at the next meet up, and we could have a discussion round there. I would like to know more about how people heard about us, etc.

**Comment by lau** [comment]
Idea: An Elixir webapp that serves as a replacement for the features the group now uses on meetup.com. Could run on Heroku for free. 
Mandrill offers free email sending: http://www.mandrill.com/

The source code could be open source here on github and people could contribute with pull requests. Could be a fun way for the group to collaborate with actual Elixir code.

But all of this requires that someone wants to spend the time to start making the app.

**Comment by gausby** [comment]
Not to put too much on my table, but I've been thinking about doing a elixir meet up group world map website for a while. I could brainstorm loudly about these ideas at the next meet up. Of course it will be open source and open collaboration—as well as a fun Phoenix project :)

One thing about meetup.com though: It is kinda like a catalogue of meet ups in a given area, and one argument to be there is the exposure.

**Comment by skovsgaard** [comment]
I'm still against meetup.com entirely. There has to be a better way to promo the group than within that walked garden.

**Comment by madsflensted** [comment]
@lau yes - had the same thought with the new pricing tiers from Heruko.

@gausby as for being discoverable, I suggest that you put together a short questionare and send out to all the meetup.com members, e.g.. "how did you discover cphex?", "what is you intention?" (going to next meeting, waiting for the right talk, just lingering...), "do you have a github account?" etc.

**Comment by gausby** [comment]
Great, let's organise some collaboration on an alternative in #24 

Also, I might do a short rant about this at the next meet up, and close this issue for now.

Good initiative, @madsflensted :+1:

**Comment by madscoaducom** [comment]
Great rant away, and then gather all the good feedback on issue #24
