### ISSUE TITLE
Let us build the forkable-elixir-meetup website

### ISSUE THREAD

**Issue by madsflensted** [cphex/cphex#24]
Based on the original idea from @gausby and the discussion in #23 I suggest we plan for a day of collaborative coding where we set out to build the basis for any Elixir meetup group to get a website up and running by simply:
1. Fork
2. Configure
3. Publish
4. Alter all you like, contribute back to original etc.

Features:
- "Sign up" (via github account)
- Github repo as primary backend
- Notification of upcoming events
- RSVP to published events
- Publish location of group and events to @gausby [Elixir-world-map](https://github.com/cphex/cphex/issues/23#issuecomment-115016837)
- (add your ideas here)

Date: TBD
Location: TBD

**Comment by madsflensted** [comment]
I suggest we target a Saturday or Sunday in August

**Comment by gausby** [comment]
Personally I got some birthdays (my brother and niece), and I do a conference called KoldskålsConf, so I will not be available August 8 + 9 and 22 + 23.

How about the first of August?

**Comment by skovsgaard** [comment]
The first would work for me. Also it's a Saturday.

**Comment by madscoaducom** [comment]
For me it would work 15.-16 or 29.-30.

The first would work for me. Also it's a Saturday.

—
Reply to this email directly or view it on GitHub
<https://github.com/cphex/cphex/issues/24#issuecomment-115212695>.

**Comment by oscarftoro** [comment]
Colaborative Coding! :tada
I can't between the 14th and 24th of July so  29th-30th of July could be an option, otherwise the 1th. August or any Saturday or Sunday of August is also fine

**Comment by gausby** [comment]
We could perhaps do this January 16, 2016.

**Comment by gausby** [comment]
@Hanspagh I suggest the old issues are closed such that it doesn't pollute the new meet up
