### ISSUE TITLE
Talk about Elixir at the Functional Programming Meetup Copenhagen

### ISSUE THREAD

**Issue by oscarftoro** [cphex/cphex#26]
The 1st of September I am giving a talk about what makes Elixir unique and interesting. The meeting is going to be at 18:00 at Prosa. The talk will be based on a comparative analysis of Elixir and other programming languages. I will present some interesting aspects of the ErlangVM, documentation, influences, concurrency primitives and how to get started. I hope that some of you want to participate in an open dialog with other programmers that want to learn more about Elixir. It is going to be fun!
Big hug,
Oscar

http://www.meetup.com/MoedegruppeFunktionelleKoebenhavnere/events/224655887/

**Comment by skovsgaard** [comment]
I'm in!

**Comment by gausby** [comment]
Nice; would it be alright if I tweet out the following then?

Would any copywriters object to @cph_ex tweeting this?

```tweet
Come and see @of_toro give a talk about Elixir at the Funktionelle Københavnere meet up September 1. http://www.meetup.com/MoedegruppeFunktionelleKoebenhavnere/events/224655887/ #myelixirstatus
```

**Comment by skovsgaard** [comment]
No objections; looks good.

**Comment by gausby** [comment]
Cool; ill tweet it then: http://twitter.com/cph_ex/status/633998757441478656

I corrected the twitter handle to Oscars actual handle (I don't know why I think he is supposed to be of_toro on twitter)…retweet away :)

**Comment by oscarftoro** [comment]
please, go ahead, but my handler has been changed to @oscarftoro though :)

**Comment by gausby** [comment]
@oscarftoro do you need any help with this, or should we close the task?

We could write some drafts for some tweets that we could post the days up til the event.

Also; if you want to have some extra eyes on your presentation I would be willing to provide them.

**Comment by oscarftoro** [comment]
Thank you!, I will let you know. I opened the issue to extend the
invitation to all of you. If the task is considered fulfilled, that is fine
with me :)

@oscarftoro <https://github.com/oscarftoro> do you need any help with this,
or should we close the task?

We could write some drafts for some tweets that we could post the days up
til the event.

Also; if you want to have some extra eyes on your presentation I would be
willing to provide them.

—
Reply to this email directly or view it on GitHub
<https://github.com/cphex/cphex/issues/26#issuecomment-132769212>.

**Comment by gausby** [comment]
It would be nice to have a place to make announcements like this; meetup.com does not give us any tools to link to a meet up in another meet up group...A twitter strategy might be our best bet, and of course we could write the Elixir Radar and ask them for a mention.

**Comment by oscarftoro** [comment]
Thank you for comming!!!!  See you on Friday! ;)

**Comment by gausby** [comment]
@oscarftoro thank you for the talk. I think this was the best talk I've seen you giving.

We need to do more collaborations with other meet up groups to broaden our reach. I really enjoyed the Q&A round afterwards; tough questions and nice to hear what people from other programming languages find odd and confusing about the beam way of life :)
