### ISSUE TITLE
Get together for the Phoenix Seminar with Jose Valim

### ISSUE THREAD

**Issue by gausby** [cphex/cphex#27]
Date and time: September 4 @ 19h (seminar will start approx. 20h our time)
Location:
> Labitat
> H. C. Ørsteds Vej 5, kld tv.
> 1879 Copenhagen
> Denmark

It is close to the Forum metro station. The seminar should start around 20h our time, and I will be there at least an hour before.

* * *

Jose Valim will give an online seminar September 4, 11 am pacific time. If my calculations are correct that would be 20 pm Copenhagen time.

  * http://pages.plataformatec.com.br/webinar-phoenix-framework-with-jose-valim

<strike>Should we meet up at a place with a projector and watch it together?</strike>

**Comment by skovsgaard** [comment]
Sounds like a good idea. Do we have any possible locations?

**Comment by gausby** [comment]
Not currently. I can ask around on twitter monday during office hours.

**Comment by niklasni1** [comment]
How many people would you expect to show up?

**Comment by gausby** [comment]
@niklasni1 Hard to tell, but at our regular meetings we muster around 15 people. This meeting would be the first of the format, and rather late in the evening compared to our usual meetings; My gut feeling says around 10 people...

**Comment by niklasni1** [comment]
Labitat?

**Comment by gausby** [comment]
Labitat could definitely be an option. Do you have access, @niklasni1 ?

I just saw that it is a friday, so most people might be out socialising with friends and/or colleagues; this might make the attendant number smaller, and harder to find an office for a venue.

I'll sign up as a paying member of Labitat (I should have done that years ago).

**Comment by niklasni1** [comment]
Yeah, I have access. Should I write to the mailing list?

**Comment by gausby** [comment]
Yes, you can do that.

But I am sorry to say that I just got reminded of an event on september 4 that I had forgot to put in my calendar, which unfortunately conflict with this event.

Does anyone want to spearhead this event and make sure it comes together? I'll tweet and update meetup.com if anyone is ready to commit.

**Comment by madsflensted** [comment]
I think this is a great idea, I wish I could join, but it is not possible this time.

**Comment by gausby** [comment]
Well, I am going to a birthday party that night at 20:30, so i could go for the seminar, and leave early.

Yeah! That is the deal; I will be there, but I cannot help cleaning afterwards, sorry.

**Comment by gausby** [comment]
So; We need:

  * A computer
  * A projector
  * Someone to sign up for the seminar (it should be free)

Unfortunately, because I have to go to a party afterwards I cannot bring my computer.

**Comment by gausby** [comment]
@niklasni1 what's the status with Labitat? Can we use that as a venue?

**Comment by niklasni1** [comment]
Shouldn't be a problem, I forgot to write, though.

**Comment by gausby** [comment]
@niklasni1 :+1:

**Comment by niklasni1** [comment]
I wrote to say we'll be occupying the kitchen from 7 to 9 because I
thought we might meet up for pizzas before. I'll be there before most
likely.

Did anybody sign up?

**Comment by gausby** [comment]
Sorry, I forgot to create the meetup announcement on meetup.com; I really don't like that site.

I've created one now: http://www.meetup.com/CPHEX-Copenhagen-Elixir/events/224945295/

**Comment by gausby** [comment]
And pizza sounds good :+1:

**Comment by skovsgaard** [comment]
I made my schedule work so I'll be there too.

**Comment by gausby** [comment]
Cool; I've updated the event description with the location and time.
