### ISSUE TITLE
Copenhagen Elixir and Erlang September 2015 Meet up

### ISSUE THREAD

**Issue by gausby** [cphex/cphex#28]
Copenhagen Elixir and Erlang September 2015 Meet Up

**Date and time**: September 23, 6 p.m.
**Location**:
> Prosa
> Vester Farimagsgade 37A
> 1606 København V
[map](https://www.google.com/maps/place/Vester+Farimagsgade+37A,+1606+København+V/@55.6787781,12.5626736,17z/)

This time around we will try peer programming session, so install Elixir and/or Erlang on your laptop and bring it (fully charged) to the meet up—we will split into groups mixing experienced Elixir/Erlang programmers with newcomers, and we will work through some problems together—at the end of the session we will compare solutions.

* * *
We need to find and decide upon:

  * [x] a venue
  * [x] a format; talks or peer programming—or a little bit of both?
  * [x] a date

<strike>As I mentioned at the last meet up; We could switch to a peer-programming type of meet ups. The thinking is to pair newcomers up with experienced Elixir or Erlang programmers and solve a task; we could then show the solution afterwards, and such.</strike>

<strike>If we want to have some talks I could give one about a Workshop project I've been working on. I think it might be in a state where I can show it to a group of people—also, a person known to me (but I will not mention any names, because I don't want to pressure people) would perhaps give a talk about working with Phoenix; and I think I heard someone had some experience with Ecto, which could be interesting as well!</strike>

<strike>I have been thinking of going to Nantes at some point, but I guess I will for sure be around Copenhagen in the latter part of September.</strike>

**Comment by madsflensted** [comment]
Last part of September works for me. 
I like the pair(mob)-programming idea, maybe we could build few Elixir exercises for your workshop app.

**Comment by gausby** [comment]
Let's settle for a date between September 21–24.

The [Funktionelle Københavnere meet up group will have a meeting September 29](http://www.meetup.com/MoedegruppeFunktionelleKoebenhavnere/events/224023667/), so we will not conflict with them; any other meet ups that could be interesting for Erlang/Elixir developers that we should take into consideration?

If not I will just pick September 22 and start looking for a venue.

**Comment by madscoaducom** [comment]
If possible I would prefer 23.

I will also see if I can think of a place.

**Comment by gausby** [comment]
@madscoaducom Wednesday works for me as well. I'll give it some time and start communicating that date.

**Comment by gausby** [comment]
I've announced September 23. A meetup.com event has been created.

Should we try out the pair programming format? If so, we need a task that the participants can solve quickly even if they do not know much about Elixir; and it should be interesting as well.

If we go with talks I think I could introduce the Workshop project I've been working on.

**Comment by skovsgaard** [comment]
I don't have a talk or anything ready, so my vote is naturally for the pairing idea. But really, either works. It'd just be nice to have a note on the meetup group telling people to weigh in on it here.

**Comment by gausby** [comment]
If we go for the pair programming format we need to find a task that is solvable within ~2 hours or so, and easy enough to grasp for new comers, yet interesting for experienced developers.

I kinda have an idea about a Hangman game. It involves pattern matching, a server process that keep the state of the game, message parsing, and the solution would require some data structures such as list, maps, etc.

**Comment by lehoff** [comment]
In 2 hours you have to be really careful with the scope.

Perhaps Yatzy scoring calculation for starters. 
Cons: No concurrency in the first iteration. 
Pros: It is great for pattern matching and working with lists.

If a beginner is to learn something there must be time for that person to try out something, fail (preferably fast) and then work with the experienced person to get something that works.

Anyway, solving the problem of the scoring has to be done sequentially, so better to start with that to get ones hands dirty.

I have a template file with all the required functions and some documentation of how they are supposed to work that we could start from. That might be considered too much guidance for some, but it would ensure that we all end up on the same page and allow us to focus more on the differences in implementations.

```Elixir
 defmodule Yatzy.Score do


  @doc ~S"""
  upper(n, ds) should return the score for the roll ds used in the slot for n number
  of eyes in the upper section of the score sheet.

  ## Examples
     iex> Yatzy.Score.upper(1, [2,3,1,2,1])
     2
     iex> Yatzy.Score.upper(2, [2,2,2,3,2])
     8
  """
  def upper(n, ds) do
    :undefined
  end

  @doc ~S"""
  chance(ds) should return the sum of the eyes on the dice.

  ## Examples
     iex> Yatzy.Score.chance([3,4,2,4,1])
     14
  """
  def chance(ds) do
    :undefined
  end

  @doc ~S"""
  yatzy(ds) should return 50 if all dice are showing the same number of eyes.

  ## Examples
     iex> Yatzy.Score.yatzy([2,3,3,3,3])
     0
     iex> Yatzy.Score.yatzy([4,4,4,4,4])
     50
  """
  def yatzy(ds) do
    :undefined
  end

  @doc ~S"""
  small_straight(ds) should return 15 for any set of dice containing the
  sequence 1-2-3-4-5 in any order.

  ## Examples
     iex> Yatzy.Score.small_straight([1,2,3,4,6])
     0
     iex> Yatzy.Score.small_straight([2,4,3,1,5])
     15
  """
  def small_straight(ds) do
    :undefined
  end

  @doc ~S"""
  large_straight(ds) should return 20 for any set of dice containing the
  sequence 2-3-4-5-6 in any order.

  ## Examples
     iex> Yatzy.Score.large_straight([5,2,3,2,6])
     0
     iex> Yatzy.Score.large_straight([6,2,4,3,5])
     20
  """
  def large_straight(ds) do
    :undefined
  end

  @doc ~S"""
  four_of_a_kind(ds) has a value when there are four of a kind in the roll and then
  its value is the total number of eyes on the dice being four of a kind.

  ## Examples
     iex> Yatzy.Score.four_of_a_kind([2,3,3,3,5])
     0
     iex> Yatzy.Score.four_of_a_kind([5,5,5,2,5])
     20
  """
  def four_of_a_kind(ds) do
    :undefined
  end

  @doc ~S"""
  three_of_a_kind(ds) has a value when there are three of a kind in the roll and then
  its value is the total number of eyes on the dice being three of a kind.

  ## Examples
     iex> Yatzy.Score.three_of_a_kind([2,3,4,3,5])
     0
     iex> Yatzy.Score.three_of_a_kind([4,1,4,2,4])
     12
  """
  def three_of_a_kind(ds) do
    :undefined
  end

  @doc ~S"""
  one_pair(ds) has a value when there is a pair in the roll and then
  its value is the total number of eyes on the dice in the pair.

  ## Examples
     iex> Yatzy.Score.one_pair([2,3,4,1,5])
     0
     iex> Yatzy.Score.one_pair([4,6,6,2,5])
     12
  """
  def one_pair(ds) do
    :undefined
  end


  @doc ~S"""
  two_pairs(ds) has a value when there is two pairs in the roll and then
  its value is the total number of eyes on the dice in the two pairs.

  ## Examples
     iex> Yatzy.Score.two_pairs([2,3,3,3,3])
     0
     iex> Yatzy.Score.two_pairs([2,4,6,2,6])
     16
  """
  def two_pairs(ds) do
    :undefined
  end

  @doc ~S"""
  full_house(ds) has a value when there is three of a kind and a pair in the roll.
  The value is the sum of the eyes on the dice.

  ## Examples
     iex> Yatzy.Score.full_house([3,3,3,3,3])
     0
     iex> Yatzy.Score.full_house([3,3,6,3,6])
     21
  """
  def full_house(ds) do
    :undefined
  end


end
```

**Comment by gausby** [comment]
@lehoff Yeah, past experience tells me that pattern matching alone can be overwhelming for a beginner*, so the example you've provided would be extremely good material for the meet up; especially because of the template—in the following discussion round it would be much easier to go: “how did you solve the `two_paris/1` problem?” in contrast to “how did you structure your OTP application for the hangman game and deal with state, etc.?”

I say we go with Yatzy…perhaps Spilhuset would be a suiting venue for this event :)

___
* Come to think of it; I should call my friend and ask if he is okay; and if he would like to have another look at functional programming.

**Comment by skovsgaard** [comment]
If they wanna host, sure, that sounds great.

**Comment by gausby** [comment]
@madsflensted have you found a venue?

**Comment by gausby** [comment]
I've changed the time to 18h, should give us some more time for playing around.

Also, Valberg are looking into a possible venue which will be great for the event (lot's of tables and power outlets for the laptops).

**Comment by lehoff** [comment]
Unfortunately I'm giving a webinar at 18.00 on the 23rd :-( 
Implementing the logic for Acquire in Elixir :-)

Would love to hear how the Yatzy experiment pans out, though.

**Comment by gausby** [comment]
I've updated the issue with location and removed the tags. Looking forward to seeing you all Wednesday.

Feel free to add to the issue if you have suggestions, ideas, and/or remarks about this event.

@lehoff will it be the same talk you gave in Norway? Anyways, looking forward to the video...

**Comment by lehoff** [comment]
Same talk as in Norway, but with a few corrections.

On 18 September 2015 at 15:08, Martin Gausby <notifications@github.com>
wrote:

> I've updated the issue with location and removed the tags. Looking forward
> to seeing you all Wednesday.
>
> Feel free to add to the issue if you have suggestions, ideas, and/or
> remarks about this event.
>
> @lehoff <https://github.com/lehoff> will it be the same talk you gave in
> Norway? Anyways, looking forward to the video...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cphex/cphex/issues/28#issuecomment-141446545>.
>



-- 
http://www.linkedin.com/in/torbenhoffmann
@LeHoff

**Comment by valberg** [comment]
One solution from today: https://gist.github.com/valberg/7a0bafff480b315a00e0 made together with @madsflensted

**Comment by KamilLelonek** [comment]
My solution: https://gist.github.com/KamilLelonek/7bbe1ccd486b7d54b262

**Comment by naruvimama** [comment]
https://gist.github.com/naruvimama/2bb2f129ca3d1866ac1f

**Comment by cheng81** [comment]
https://gist.github.com/cheng81/8f7837fb7a07b179803f

**Comment by lehoff** [comment]
Some observations across the solutions:

   - small_straight should only return 15 for [1,2,3,4,5] - large_straight
   20 for [2,3,4,5,6] - add some tests for that.
   - a full house can be used as two pairs - not all solutions allow that.
   A test case or two?
   - yatzy can be used as four of a kind. Tests?
   - four of a kind can be used as three of a kind. Tests?
   - three of a kind can be used as a pair...
   - when using Enum.filter a thing like &(&1==n) is a good way to specify
   getting all n's out.
   - be more agressive with patterns - see
   http://beamster.org/yatzy-pattern.html

Cheers,
Torben

2015-09-23 21:55 GMT+02:00 Francesco Zanitti <notifications@github.com>:

> https://gist.github.com/cheng81/8f7837fb7a07b179803f
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cphex/cphex/issues/28#issuecomment-142710838>.
>



-- 
http://www.linkedin.com/in/torbenhoffmann
@LeHoff

**Comment by gausby** [comment]
If anyone is interested in my solution it can be found here: https://github.com/gausby/cphex_yatzy_solution/blob/master/lib/yatzy/score.ex

As I said when I showed the solution: I try to shift the problem into the realm of pattern matching; so most of the magic happens in the helper function that transform the data into something that is easier to pattern match on—at least that was the philosophy.

**Comment by madsflensted** [comment]
@lehoff thank you for the detailed feedback. I get the feeling that you
deliberately omitted those tests (like any good teacher) ;-)

Actually the exercise was perfect,  and we had some good discussions about
the different solutions,  and had fun trying different ways of solving the
problem.

I suggest we gather up one cphex master version that we can use as a basis
for our next hands on meetup, where we talked about exploring the Yatzy
univers further.

**Comment by cheng81** [comment]
ooook, so the rules allows for something like:
score([5,5,5,5,5]) -> 10 
(using the "pair" rule)  instead of selecting by default the rule that produces the highest score?
Why would anyone do that :p ? anyway, I'll see what I come up with :)

**Comment by gausby** [comment]
@cheng81 At every turn you have to pick a score rule, and you can only use that rule once. So sometimes you end up in a situation where you have nothing to pick; then you might pick something like "yatzy" that is really hard to achieve.

The game is over when the players has no more rules to pick from.

**Comment by madsflensted** [comment]
Maybe we should spend 20 min actually playing next time?  :-)

**Comment by gausby** [comment]
@madsflensted It. Is. On!

**Comment by lehoff** [comment]
I have now thrown in solutions to all combinations @
http://beamster.org/yatzy-pattern.html

On 24 September 2015 at 00:02, Martin Gausby <notifications@github.com>
wrote:

> If anyone is interested in my solution it can be found here:
> https://github.com/gausby/cphex_yatzy_solution/blob/master/lib/yatzy/score.ex
>
> As I said when I showed the solution: I try to shift the problem into the
> realm of pattern matching; so most of the magic happens in the helper
> function that transform the data into something that is easier to pattern
> match on—at least that was the philosophy.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cphex/cphex/issues/28#issuecomment-142744209>.
>



-- 
http://www.linkedin.com/in/torbenhoffmann
@LeHoff

**Comment by madsflensted** [comment]
I can bring 2-3 Yatzy sets

**Comment by lehoff** [comment]
Hi Mads,

At first I left out the corner cases out of sloppiness, but when I
revisited the description I decided that I wanted to be able to question
what was going on in the code and if the tests were good enough to phantom
the full rule set.

Getting a canonical version would be very good.

The next natural step would be to create a Yatzy.ScoreSheet which can keep
track of which combinations have been used and tally up the score incl the
bonus.

When that is in place one can start to do multiplayer - there are some
options for how to do it digitally... one does not have to wait turns,
i.e., we could have parallel turns where one only syncs after a turn has
been done.

And it is screaming in our faces that we should write a Phoenix web server
and an Elm front end.
But I would start with just a Phoenix front end before opening up the Elm
side of things.

Cheers,
Torben

On 24 September 2015 at 08:52, Mads Flensted-Urech <notifications@github.com
> wrote:

> @lehoff thank you for the detailed feedback. I get the feeling that you
> deliberately omitted those tests (like any good teacher) ;-)
>
> Actually the exercise was perfect, and we had some good discussions about
> the different solutions, and had fun trying different ways of solving the
> problem.
>
> I suggest we gather up one cphex master version that we can use as a basis
> for our next hands on meetup, where we talked about exploring the Yatzy
> univers further.
> On Sep 24, 2015 00:02, "Martin Gausby" <notifications@github.com> wrote:
>
> > If anyone is interested in my solution it can be found here:
> >
> https://github.com/gausby/cphex_yatzy_solution/blob/master/lib/yatzy/score.ex
> >
> > As I said when I showed the solution: I try to shift the problem into the
> > realm of pattern matching; so most of the magic happens in the helper
> > function that transform the data into something that is easier to pattern
> > match on—at least that was the philosophy.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/cphex/cphex/issues/28#issuecomment-142744209>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cphex/cphex/issues/28#issuecomment-142830793>.
>



-- 
http://www.linkedin.com/in/torbenhoffmann
@LeHoff

**Comment by madscoaducom** [comment]
I plan to start Elm group with first meetup in October.

I want to use the hands on model from day one,  and thought the Yatzy idea
could be reused as a starting point

So maybe we can get some cooperation going :-)

**Comment by lehoff** [comment]
Elm group would be awesome!

Yatzy could work really well with Elm and it is not too complicated to code
- even if the pattern matching cannot be done as devilishly simple as in
Elixir... evil type system ;-)

I would do it on the Elm side exclusively for starters and then use the two
versions to look at how to marry the two worlds nicely. Elm is pretty heavy
on its model and the wire to the logic on the server side has to be thought
through in order to get something that is smooth.


On 24 September 2015 at 11:18, Mads Flensted-Urech <notifications@github.com
> wrote:

> I plan to start Elm group with first meetup in October.
>
> I want to use the hands on model from day one, and thought the Yatzy idea
> could be reused as a starting point
>
> So maybe we can get some cooperation going :-)
>
> On Sep 24, 2015 10:42, "Torben Hoffmann" <notifications@github.com> wrote:
>
> > Hi Mads,
> >
> > At first I left out the corner cases out of sloppiness, but when I
> > revisited the description I decided that I wanted to be able to question
> > what was going on in the code and if the tests were good enough to
> phantom
> > the full rule set.
> >
> > Getting a canonical version would be very good.
> >
> > The next natural step would be to create a Yatzy.ScoreSheet which can
> keep
> > track of which combinations have been used and tally up the score incl
> the
> > bonus.
> >
> > When that is in place one can start to do multiplayer - there are some
> > options for how to do it digitally... one does not have to wait turns,
> > i.e., we could have parallel turns where one only syncs after a turn has
> > been done.
> >
> > And it is screaming in our faces that we should write a Phoenix web
> server
> > and an Elm front end.
> > But I would start with just a Phoenix front end before opening up the Elm
> > side of things.
> >
> > Cheers,
> > Torben
> >
> > On 24 September 2015 at 08:52, Mads Flensted-Urech <
> > notifications@github.com
> > > wrote:
> >
> > > @lehoff thank you for the detailed feedback. I get the feeling that you
> > > deliberately omitted those tests (like any good teacher) ;-)
> > >
> > > Actually the exercise was perfect, and we had some good discussions
> about
> > > the different solutions, and had fun trying different ways of solving
> the
> > > problem.
> > >
> > > I suggest we gather up one cphex master version that we can use as a
> > basis
> > > for our next hands on meetup, where we talked about exploring the Yatzy
> > > univers further.
> > > On Sep 24, 2015 00:02, "Martin Gausby" <notifications@github.com>
> wrote:
> > >
> > > > If anyone is interested in my solution it can be found here:
> > > >
> > >
> >
> https://github.com/gausby/cphex_yatzy_solution/blob/master/lib/yatzy/score.ex
> > > >
> > > > As I said when I showed the solution: I try to shift the problem into
> > the
> > > > realm of pattern matching; so most of the magic happens in the helper
> > > > function that transform the data into something that is easier to
> > pattern
> > > > match on—at least that was the philosophy.
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <https://github.com/cphex/cphex/issues/28#issuecomment-142744209>.
> > >
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/cphex/cphex/issues/28#issuecomment-142830793>.
> > >
> >
> >
> >
> > --
> > http://www.linkedin.com/in/torbenhoffmann
> > @LeHoff
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/cphex/cphex/issues/28#issuecomment-142858647>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cphex/cphex/issues/28#issuecomment-142865042>.
>



-- 
http://www.linkedin.com/in/torbenhoffmann
@LeHoff

**Comment by emilbayes** [comment]
@madsflensted  I know @malthejorgensen is messing around with some Elm stuff

**Comment by malthejorgensen** [comment]
:+1: Yeah, I'm definitely up for Elm meetup in Copenhagen!

**Comment by madscoaducom** [comment]
Coo!

Will keep you in the loop.

**Comment by gausby** [comment]
Thanks for a great meet up. I am going to close this issue so we can start preparing and organising the October meet up. This one will be a big one, it will be the one year anniversary edition!

Personally I am excited about the Elm meet up. Let me know if there are anything I can do to help out.

Yet again. Thanks to @valberg for finding the venue, Prosa, and thanks to @lehoff for creating and providing the yatzy score problem.

**Comment by madsflensted** [comment]
Elm group is now a thing :-) 
Setting up using the @gausby's model was a breeze
