### ISSUE TITLE
October 2015 meet up

### ISSUE THREAD

**Issue by gausby** [cphex/cphex#29]
Copenhagen Elixir/Erlang 2015 meet up.

Date: Wednesday, October 21 2015
Time: 18h
Location:
> Founders House
> Njalsgade 19D
> 2300 Copenhagen
> Denmark

Agenda: We will work on some tasks together. Experienced Elixir/Erlang developers mixed with newcomers.

* * *
We need to find and decide upon:
  * [x] a format; hands on problem solving, talks and presentations, or something else?
  * [x] a venue
  * [x] a date and a time
  * [x] depending on which format we will go with, we will either need talks or a problem to work on

***
<strike>Let's organise a meet up for October 2015. This will be our one year anniversary as October 20th 2014 was the date of our first meet up<sup><a href="#footnote-1">1</a></sup>.</strike>

* * *
<sup id="footnote-1">1</sup> https://github.com/cphex/cphex/issues/6 - Meeting Face to Face

**Comment by madscoaducom** [comment]
Date suggestions:

Wednesday 21.
Friday 23.
(Tuesday 20.)

👍 on the hands on format

**Comment by gausby** [comment]
I will go to France October 1st–14th, so of course I will vote for a date after the 14th.

We could have the meeting on Tuesday October 20, but as this is the day of our anniversary—which really only have significance for few os us, as it was only three of us who did attend this original meet up—I would like to suggest an extraordinary event where we go to Paludan's Bogcafe and eat some chili con carne to celebrate the anniversary, and talk about the year and how far we have come; returning to the original format of a few people meeting and trying to figure out what Elixir really is.

So, I suggest Wednesday 21 for a full blown meet up; with hands on *pair* programming sessions, and Tuesday 20 for a social get together at Paludan.

**Comment by skovsgaard** [comment]
I like the idea of splitting the social from the regularly scheduled programming. However, another option there is to do Friday 23rd and go get a beer or something afterwards (although I guess it ruins the nostalgia if it's not at Paludan). Ultimately, either format works for me.

**Comment by gausby** [comment]
My thinking: Fridays doesn't really work because offices are closing down for the weekend, and employees often go for a beer with their colleges and/or friends, or are just busy going home to enjoy the weekend.

I have no data to back this up; it is just my personal experience.

**Comment by skovsgaard** [comment]
You're probably right. The 20th/21st option works fine too.

**Comment by madscoaducom** [comment]
So split into 2 events,

20. Social, open to anyone with a preference for nostalgia.  👍 for
Paludan.  Time would have to be 19.30 for me to attend
21. Meet up

**Comment by gausby** [comment]
I like this plan. Let's start looking for a venue for the 21st.

It seemed that everyone attending the last meet up liked the hands-on session, so I suggest that we start thinking about a problem we can work on for this meet up.

I will start a different issue for the social anniversary meet up. I need to figure out if I should talk to Paludan about reserving a table, or if we will only be three people showing up; Copenhagen Elixir 2014-style :)

**Comment by skovsgaard** [comment]
I still like the key/value idea suggested for last time, as an exercise. It'd be a cool way into OTP and handling state.

**Comment by gausby** [comment]
@skovsgaard +1 I can try to ask our friends in Stockholm Elixir if they have some material for a session like this; I think they have done this scenario like this.

That said, other ideas are still welcome!

**Comment by gausby** [comment]
I've created a new issue about the October 20th social get together: https://github.com/cphex/cphex/issues/30

**Comment by emilbayes** [comment]
The key/value idea seems very close to what they teach you in [Introduction to Mix](http://elixir-lang.org/getting-started/mix-otp/introduction-to-mix.html) (if you need inspiration)

I'll try to make both events if I can :)

**Comment by gausby** [comment]
The "Introduction to Mix" article is a good one, but it cover a bit too much for one session. If we are going to make a key-value store it would be sufficient to make an interface for a Agent, spin it up in a process and supervise it.

**Comment by skovsgaard** [comment]
I like the Agent option. Is that what the Stockholm people used?

**Comment by gausby** [comment]
Just a reminder: We still need a venue for this meet up. The venue should have internet, places for the participants to sit with their laptops, and preferably have electrical outlets for their chargers. It would also be nice if the room had a projector so we can compare solutions on the big screen at the end of the event.

**Comment by gausby** [comment]
@skovsgaard I haven't heard from the Stockholm people yet, as some of them has been out travelling for ElixirConf in Austin. I can try to ping them again.

**Comment by skovsgaard** [comment]
No rush. Also as far as venue goes, I can see if there's a place free here. It's gonna be as dark and boardroom-y as always but it's something to try if we don't find another venue.

**Comment by gausby** [comment]
@skovsgaard The room with the big screen telly would be fine; the one we switched to at the last meeting hosted there.

**Comment by skovsgaard** [comment]
Yeah, it's about the same size as the place at PROSA, so it'd definitely work for that. It's just still a problem with the silly amount of locked doors. But I can absolutely see if that room is free.

**Comment by gausby** [comment]
I got in contact with the people from Stockholm Elixir, and this is the material they had on their mob/pair programming event where they did a key-value store: https://github.com/DevL/MobValueStore

Lennart also wrote a blog post about his experiences organising that event: http://codecoupled.org/2015/03/19/a-mob-of-mobs/

**Comment by madscoaducom** [comment]
It sounds like a fun exercise, and it could also be fun to try the mob
form. If we have the same number of participants as last meetup, maybe we
should plan for 2 groups?

**Comment by gausby** [comment]
@madscoaducom yep, let's decide on the day; so far 5 people has RSVP'ed on the dreaded meetup.com page

**Comment by gausby** [comment]
But I fear that the key-value task might be a bit hairy for a beginner; perhaps I should write Torben a mail and ask for his advice. I'll do that when I return from France; need to pack my stuff now and prepare for the flight…

**Comment by skovsgaard** [comment]
Should I still check about getting a room here or did other venue options come up?

**Comment by gausby** [comment]
If the key-value project is too crazy for a 2 hour meet up I could prepare some exercises where we reimplement functions from the Enum-module. It is inspired by a task from exercism, and it is pretty fun; the participants would learn about working with lists, recursion, pattern-matching and the like.

**Comment by gausby** [comment]
@skovsgaard and yeah, we might need to opt for e-conomic; I haven't heard from anyone else :-/

We need to provide internet, so we need to get the password for the guest wifi.

**Comment by gausby** [comment]
What do you think about this: https://github.com/cphex/enum_workshop/blob/master/lib/enum_workshop.ex ?

**Comment by sqbell** [comment]
Hi. Me and two other guys (@lunich, @kukula) currently working in Malmö would really like to join you on the next meetup. We don't have much experience in Elixir yet (all three of us are RoR developers) but are interested in it and would love to learn more.

**Comment by skovsgaard** [comment]
You're more than welcome. We're still not settled on the venue right now, so the best advice I can give now is to keep an eye on this issue and we'll get that sorted out so we have a place to point you to :)

**Comment by gausby** [comment]
@sqbell cool, the next meet up is tomorrow, and it is a hands-on session so you can benefit from bringing your laptops. We will be working through some exercises, and I hope that these will give you a whirlwind tour of the language.

If you can't join tomorrow we can find a date better suited for you for the November meet up :)

**Comment by bareza** [comment]
Is this still happening? it seems there is still a problem with finding a proper venue.

**Comment by gausby** [comment]
Jonas will ask if he can borrow a meeting room at his office tomorrow morning. We will announce something as soon as we know; either way I will work super fast tomorrow and find a place.

I really don't want to cancel anything :)

**Comment by bareza** [comment]
Good to know! I found out about this an hour ago. I have to shift around some stuff tomorrow to make it. Though I will probably just sit in the corner by myself and digest some of Dave Thomas book on the subject, but I want the feel of a community.

**Comment by gausby** [comment]
We got a venue. Thanks to Founders House. I'll update all the pages and info when I get home.

Phew, that was a close call :)

**Comment by skovsgaard** [comment]
Yay!

**Comment by Hanspagh** [comment]
:+1:

**Comment by madscoaducom** [comment]
👍

**Comment by Hanspagh** [comment]
Bit confused about location, is it the 1. Or 2 floor

**Comment by emilbayes** [comment]
@Hanspagh 1st floor, the stairs are on the "back side". I think @gausby is downstairs directing people up :)

**Comment by gausby** [comment]
Thanks for a great meet up. I think we all had and learned a thing or two about functional programming and Elixir.

Founders House was a great location and an awesome host. I hope we can have future events there. In this regard I have to give a special thanks to @kevinsimper from Blackbeard, who facilitated the connection to Founders House on such short notice. Thank you very much.

In the future we will try to get some backup venues, to prevent us from ending up in the same situation where we haven't got a venue the day before the event. It is good and healthy to rotate the venues from time to time, but we got to have some stability. I am truly sorry if any of you got confused about the venue situation for this event, and didn't end up going because of this uncertainty.

If any of you have ideas, suggestions, and thoughts about how we can make these events even better I would like to hear them; and once again thank you for showing up and help putting this event together.

See you in November; and remember that our friends at [elmcph](https://github.com/elmcph/elmcph) will have their first meet up Wednesday next week.

Let's start organising the event(s?) for November.

**Comment by kevinsimper** [comment]
@gausby You are welcome, it was fun and I want to join next time as well! :smile:
