### ISSUE TITLE
Processes, agents and messages

### ISSUE THREAD

**Issue by DotNetNerd** [cphex/cphex#3]
It could be interesting with a talk about how to work with agents and messagepassing in Elixir at real scale. I am thinking a deepdive on the concepts and coverage of patterns for a real world architecture.

**Comment by gausby** [comment]
I have thought about giving a talk on this subject. Maybe in June.

**Comment by gausby** [comment]
I will give a talk about processes this evening. I think this solves this issue. The presentation can be found here: https://github.com/gausby/processes_presentation
