### ISSUE TITLE
One year anniversary get together at Paludan

### ISSUE THREAD

**Issue by gausby** [cphex/cphex#30]
October 20th will mark the day of our one year anniversary.

Back then the Copenhagen Elixir meet up consisted of a couple of people sitting around a table at a café, talking about what Elixir is, what this OTP thing does, and generally sharing the excitement and our understanding of this language and environment.

We have been thinking about doing a get together in the same style, at the same cafe that we did the original meet up at, and as always everyone is invited.

So join us **October 20th at 19:30** at:
> Paludan Bog&Café
> Fiolestræde 10-12
> 1171 København K

If we are more than 7 people joining we might have to place a reservation, so please RSVP.

<small>Small print: Food and drinks will be on participants own dime, Copenhagen Elixir/Erlang is a non-profit organisation and don't receive any sponsorship; awesome as it would be we can't afford buying food and drinks for anyone. You don't need to buy anything at the cafe to attend the event; That said, the cafe has really reasonable prices for foods and drinks.</small>

**Comment by skovsgaard** [comment]
RSVP: I'm in.

**Comment by emilbayes** [comment]
I'm in!

**Comment by madscoaducom** [comment]
I will be joining.

**Comment by gausby** [comment]
That makes four :)

I'll announce both the regular event and this event on meetup.com tomorrow.

**Comment by gausby** [comment]
Better late than never; I've created a meet up page for this event. http://www.meetup.com/CPHEX-Copenhagen-Elixir/events/225722571/

**Comment by emilbayes** [comment]
I won't make it tomorrow, but will definitely be there Wednesday :worried:

**Comment by gausby** [comment]
Thanks for a great meet up. It definitely had that old school feeling ^_^

**Comment by madscoaducom** [comment]
Great evening - looking forward to see what year two will be like!
