### ISSUE TITLE
Find a fixed schedule for the regular monthly meet ups

### ISSUE THREAD

**Issue by gausby** [cphex/cphex#31]
Up until now we have found a date for the regular monthly meet ups as we go, but I guess it would be easier for everybody if we set a fixed day for our monthly meet up; like CopenhagenJS has a meet up every third Thursday of the month; Funktionelle Københavnere has a meet up every fourth Tuesday of the month and so forth.

I suggest that we consider **every third Tuesday of the month the day of our monthly meet up.**

My reasoning: It is easier to tell people to meet us at a fixed day; it is easier to strike deals with venues, and in general it is easier to plan around.

Any thoughts?

**Comment by Hanspagh** [comment]
I think its a good idea, the only downside could be that less people would be able to attend since the date isn't flexible anymore.

**Comment by gausby** [comment]
@Hanspagh We will always have the problem that some people cannot attend on a specific date. The good thing about picking a fixed date is that everyone has something to plan around.

**Comment by Hanspagh** [comment]
@gausby  Agreed and as I said I think it's a great idea

**Comment by skovsgaard** [comment]
I'm on board. Didn't we originally talk about it being the something-th something of every month but got away from it? Or was that the third tuesday?

**Comment by valberg** [comment]
I'm in :+1: Let us give it a try and evaluate after a couple of times :smile:

**Comment by gausby** [comment]
Cool. I've created a meeting for November 17; which is the third Tuesday of November.

I think the planning thread will be cleaner now that we don't have to discuss which date to do the event. Now we can focus more on planning the event itself. I really like this :)
