### ISSUE TITLE
Copenhagen Elixir and Erlang November 2015 Meet Up

### ISSUE THREAD

**Issue by gausby** [cphex/cphex#32]
<h3>Copenhagen Elixir and Erlang November 2015 Meet Up</h3>

**Date and time**: November 17 @ 18h 
**Location**:
> <strong>Prosa</strong>
> Vester Farimagsgade 37A
> 1606 København V
> [map](https://www.google.com/maps/place/Vester+Farimagsgade+37A,+1606+København+V/@55.6787781,12.5626736,17z/)

We will work on an exercise in groups, so bring your laptops.

* * *
<h3>Please help out</h3>

We are working on an exercise for the event. Please help out with pull requests and suggestions at the exercise repo https://github.com/cphex/yatzy_score_card

<strike>What should we do at this meeting? Should we do talks or another workshop session? A mixture?

  * Workshop session
  * Talks
  * Both

If we go for a workshop session we would need a task to work on. If we go for talks we need people who can give a presentation. Either way, let's start making some noise about this event.</strike>
* * *
*About the date. November 17 is the third Tuesday of November. We will go with the third Tuesday of the month to try out having a fixed date for these meet ups, which should make it easier for the participants to plan around, and easier for us to find venues for future meet ups. We will evaluate this decision when we have tried it a couple of times. Please refer to #31 if you have comments about this.*

**Comment by skovsgaard** [comment]
It sounded like you had a talk idea last time, so maybe we could do both. I'm not sure how long a talk you're imagining but both seems doable, time wise.

**Comment by Hanspagh** [comment]
I really enjoyed the hands on exercises last time, but a mix could work as well. Maybe some exercises related to the talk?

**Comment by madscoaducom** [comment]
What about this format?

- Short introduction to topic and exercise (aprox 20 min)
- Exercise related to the topic (aprox 1.5 hour)
- Comparing solutions (aprox 30 min)

**Comment by madscoaducom** [comment]
@gausby mentioned gproc - could that be a topic?

I think it would be good to do some OTP exercise

**Comment by gausby** [comment]
gproc is a bit too hairy—I am constantly switching between a state of "I got this!" to "what the what-now?!".

But for some reason I am thinking tic-tac-toe; We could implement a tic-tac-toe game server using OTP.

**Comment by madscoaducom** [comment]
Sound like at fun idea!

**Comment by gausby** [comment]
I just did a mail exchange with Torben where I asked for his suggestions for a simple process exercise. He suggested a Yatzy scoresheet exercise. This could be implemented as a process containing an agent. The exercise would also involve creating an API to handle incoming messages.

Any comments about this? Any other ideas? We only have 7 days to prepare, so I could go ahead with defining the yatzy scoresheet, an introductory presentation to the task, and creating a repo that we all can fork from.

**Comment by madscoaducom** [comment]
👍

**Comment by Hanspagh** [comment]
:+1: Lets continue down the Yatzy road

**Comment by kukula** [comment]
:+1:

**Comment by madsflensted** [comment]
Still like the Yatzy idea.

For future inspiration (or contribution) I just saw [this exercise repo](https://github.com/doomspork/elixir-school)

**Comment by madsflensted** [comment]
A little late with this, but it was a great evening. Thanks to @gausby for setting up the exercise - it worked out really well!
