### ISSUE TITLE
Copenhagen Elixir and Erlang December 2015 meet up

### ISSUE THREAD

**Issue by gausby** [cphex/cphex#33]
Copenhagen Elixir and Erlang meet up, December 2015. We will be doing some pair programming, so bring your laptop.

*Date and time*: December 15, 2015 @ 18h
*Location*:
> Prosa
> Vester Farimagsgade 37A
> 1606 København
> Denmark
> [Map](https://maps.google.com/maps?f=q&hl=en&q=Vester+Farimagsgade+37A%2C+1606%2C+dk)

* * * 
Let us do a meet up in December. Let's go with the third Tuesday of December, which would be December 15th.

Should we do talks or some tasks?

**Comment by gausby** [comment]
Considerations: December is a busy month for most people so I guess we should expect few people at this one. Even though I would like to ask some "big name" to give a talk, so we can get some attention to the group, I think we should try that in January or February instead.

So; my vote is on another round of pair-programming.

**Comment by skovsgaard** [comment]
Good idea holding off on a bigger talk-event. Does anyone have ideas on possible pairing tasks? I really liked getting into OTP more. Maybe we could think up a way to use GenEvent for something.

**Comment by madsflensted** [comment]
How about building the game engine to tie together our Yatzy efforts?

Something where you could start a new game, given list of players, each
would get a Scorecard.
We could build a "roll dices" proces,
Each player (shell process=) can roll and hold and submit scores.

Events could be sent, and we could have a leader board?

**Comment by gausby** [comment]
@skovsgaard From my understanding `GenEvent` should be avoided. I recall something about issues with recovering from errors. I am not sure that we should put some teaching material together on GenEvent, but I want dig into this, because it bugs me that I've stopped looking at GenEvent but can't remember why.

@madsflensted I don't know if it is too complex for a single session. My gut tells me that it would require multiple FSMs. I think we need to break it up a bit :)

**Comment by skovsgaard** [comment]
Okay, so I just found some [twitter talk](https://twitter.com/josevalim/status/589844284230279168) where some of the stuff about GenEvent being dangerous comes up. We could leave it be and go with either other behaviors or simply make a subset of the game engine. Maybe just the die-rolling or a lobby type way of matching players. Either or but naturally the whole thing would be a bit much for a single meetup.

**Comment by lehoff** [comment]
Stay off GenEvent - it is not necessary for this kind of product.
It is more for monitoring and metrics, i.e., enterprise stuff.

You might need some pub/sub - I have a simple library called ogma for that.

I would focus on getting the components to work one by one and then
consider using Phoenix to provide a nice front end, but that is down the
line.



On 25 November 2015 at 15:17, jsc <notifications@github.com> wrote:

> Okay, so I just found some twitter talk
> <https://twitter.com/josevalim/status/589844284230279168> where some of
> the stuff about GenEvent being dangerous comes up. We could leave it be and
> go with either other behaviors or simply make a subset of the game engine.
> Maybe just the die-rolling or a lobby type way of matching players. Either
> or but naturally the whole thing would be a bit much for a single meetup.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cphex/cphex/issues/33#issuecomment-159619497>.
>



-- 
http://www.linkedin.com/in/torbenhoffmann
@LeHoff

**Comment by skovsgaard** [comment]
Do we have any objections to the 15th or are we settled on that?

**Comment by gausby** [comment]
I think sticking to the third Tuesday of the month is a good plan, but if anyone can see a problem with that date we could move it—but personally I think consistency will help in the long run.

**Comment by gausby** [comment]
Prosa has been kind enough to host us again. I've updated the issue with location and time.

Now we just need a task. Has anyone come up with a good problem to work on?

**Comment by gausby** [comment]
How about this task: build a tcp/ip ping server using :gen_tcp

The participants will learn about how to use Erlang modules from Elixir. A bit about accepting connections and sending and receiving messages via tcp. Perhaps all wrapped in a genserver, perhaps helped by the Elixir module Connection.

At the end of the session we should be able to ping each other's machines.

**Comment by gausby** [comment]
Okay; I haven't heard any objections to the `:gen_tcp` / Ping-server workshop. It doesn't fit into the yatzy theme, but eventually we could do some networked yatzy.

I will go ahead with the ping-server idea, if nobody comes up with anything better by the end of tomorrow (Saturday). Très cool ?

**Comment by valberg** [comment]
:+1: from here!

**Comment by madsflensted** [comment]
I won't be able to make it, but I think it sounds like a good challenge,
and I will try to work on it from home instead.

**Comment by gausby** [comment]
Okay. I'll start preparing and have something ready by Tuesday ^_^

**Comment by giulioungaretti** [comment]
what's the level expected ?

**Comment by gausby** [comment]
@giulioungaretti We will pair up experienced Elixir/Erlang developers with newcomers, so even someone who walks in from the street and sees the environment for the first time should be able to have fun and learn something.

**Comment by lehoff** [comment]
Hi Martin,

I think the ping-server is a good idea.
Try to keep it close to the metal, i.e., avoid Connection.

My reason for this advice is to make sure as much of the underlying Erlang
architecture can be learned.
Abstractions are cool, but you need to know what is going on on the Erlang
level to really make the most of Elixir.

I'm afraid I won't be able to make it - work requires some extra attention
at the moment.

Cheers,
Torben

On 11 December 2015 at 14:54, Martin Gausby <notifications@github.com>
wrote:

> Okay; I haven't heard any objections to the :gen_tcp / Ping-server
> workshop. It doesn't fit into the yatzy theme, but eventually we could do
> some networked yatzy.
>
> I will go ahead with the ping-server idea, if nobody comes up with
> anything better by the end of tomorrow (Saturday). Très cool ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cphex/cphex/issues/33#issuecomment-163941429>.
>



-- 
http://www.linkedin.com/in/torbenhoffmann
@LeHoff

**Comment by gausby** [comment]
Thanks for a great meet up, and thanks for a great year.

It wasn't the biggest meet up ever, but nonetheless it turned out great. I think that it is safe to say that mob-programming works out fine when we are around five people; I think that everybody learned something—I know that I did.

We could use the TCP connection acceptor code that @skovsgaard ended up with for an upcoming network protocol session. Perhaps we could make it into a chat server, or do a yatzy-game-protocol.

Once again, thanks for showing up, and I hope to see you all at futur meet ups.
