### ISSUE TITLE
Copenhagen Elixir and Erlang Meet Up, January 2016

### ISSUE THREAD

**Issue by gausby** [cphex/cphex#34]
**Date and time**: January 19, 18h00
**Location**: 
> Woumedia
> Pakhus 47
> Sundkaj 7
> 2100 København
> [map](https://www.google.com/maps/place/Sundkaj+7,+2100+København+Ø,+Denmark/@55.7091751,12.6004012,3a,90y,31.55h,68.44t/)

* * *
Please post ideas for a pair programming exercise, or come forward with a talk if you have something that you would like to show.

**Comment by gausby** [comment]
Woumedia has offered to host this meet up. I've updated the issue with the location.

**Comment by madsflensted** [comment]
I am not going to make it. Will be looking forward to February!

**Comment by Hanspagh** [comment]
Sadly I won't make it either,  see you in February

**Comment by skovsgaard** [comment]
Are we still on, even? Judging by meetup.com, we're gonna be 2, then. I'm still up for meeting and working on stuff, but that may be a bit short of needing a venue for it.

**Comment by gausby** [comment]
I say we go the the venue. I sure does look dismal, but sometimes people show up who has not signed up to the event on meetup.

So, I'll inform the venue about the issue; I suggest that we will be there on time and stay for an hour or so to see if somebody shows up.

**Comment by gausby** [comment]
Oh, we are actually 5 now! Let's just continue as planned.

**Comment by gausby** [comment]
I've created a repo with a task we can work on here: https://github.com/cphex/pwiki_workshop

The idea is to create a simple Wiki using the Phoenix Framework.

**Comment by niklasni1** [comment]
I'll be there. Cool project.

**Comment by gausby** [comment]
If any of you have problems finding the venue, text me on twitter @gausby and I'll help you.

**Comment by mark-jordalew** [comment]
I had awful problems getting to the venue, hence my non-arrival. I
encountered fences and barriers on every attempt. At about 19:00 we gave up
and went home. I'll try again in February. :)

**Comment by gausby** [comment]
I am sorry to hear that, Mark. We will try to find a venue closer to city center for the February meet up.

**Comment by mark-jordalew** [comment]
That would be good. Did everyone else make it? I'm an erlang newbie and I
have not touched elixir as yet so you didn't miss much with me not being
there. :)

**Comment by gausby** [comment]
We were three people, so it was the smallest meet up in a long while.

And if you are new to the platform we definitely missed out. The group is here to get newcomers up to speed and spreading the good word of the beam.

**Comment by niklasni1** [comment]
I, too, failed to find the venue... Keep your Open Street Map updatet :/

**Comment by mark-jordalew** [comment]
The pattern matching from binary to other types is so sexy :) (beam is the
binary library, right?) I have big plans for using that ;)

**Comment by gausby** [comment]
BEAM is the name of the current Erlang virtual machine. But yeah; pattern matching on binaries are super convenient :)

Other than that. Woumedia had an awesome office, so we could use it again later in the year, when it is brighter and easier to find. If we do that I will provide a map and directions, because it is easier than google maps suggest. My bad for not providing that this time around, and I am sorry. Next time we will find a venue closer to city center.

Thanks to Woumedia for hosting.

**Comment by mark-jordalew** [comment]
Don't worry about it, I have never seen the docks so .... intimately ... at
night. Looking forward to Feb.
