### ISSUE TITLE
Copenhagen Elixir and Erlang January Hackathon

### ISSUE THREAD

**Issue by gausby** [cphex/cphex#35]
**Date and time**: January 16, around noon
**Location**:
> Prosa
> Vester Farimagsgade 37A
> 1606 København
> Denmark
> [Map](https://maps.google.com/maps?f=q&hl=en&q=Vester+Farimagsgade+37A%2C+1606%2C+dk)
* * * 

Let's do a hackathon. Everyone is free to do what they want, there are no competition. If people need something concrete to work on we have had #24 open for a while.

We might also be able to do a seminar on Elixir and/or Erlang.

Please add to this issue about an agenda; when should we start? Should we reserve some time to present what we have done?

**Comment by lukelex** [comment]
@gausby I've been working sparingly on a OS project, http://elixular.com/, to teach myself some elixir. We could, potentially, work on it.

**Comment by gausby** [comment]
@lukelex cool. I guess we could do a shout out for projects at the introduction. Then people could come forward with their projects, introduce them, and people could join in groups if they find something interesting.

I've been to hackathons that was structured like that. I think it worked out nicely.

**Comment by nandanrao** [comment]
Noticed this is the same weekend as [Copenhackathon](https://www.eventbrite.com/e/copenhackathon-registration-19953615802), would it make sense to combine?

**Comment by valberg** [comment]
Ah nice @nandanrao! Although I'm not personally up for the classic hackathon setup. I'm more down with a "hackday" where we sit around and hack on stuff without a deadline. Maybe that's just me though 🙂

Also the Copenhackathon website says "As a participant you are expected to be part of the event from start to end." and I have other plans the 17th.

**Comment by nandanrao** [comment]
I'm with you as far as my general preferences, so understood! I just
comitted to going to that hackathon already and was hoping to drag everyone
else with me if i could :D
