### ISSUE TITLE
Copenhagen Elixir and Erlang Meet Up, February 2016

### ISSUE THREAD

**Issue by gausby** [cphex/cphex#36]
**Date and time**: February 16, 18h00
**Location**: 
> <strong>Prosa</strong>
> Vester Farimagsgade 37A
> 1606 København V
> [map](https://www.google.com/maps/place/Vester+Farimagsgade+37A,+1606+København+V/@55.6787781,12.5626736,17z/)

Directions: The venue is pretty close to Vesterport Station and the Vester Farimagsgade bus stop. We will be sure to hang a sign on the door with contact information. If you are unable to find it try sending a twitter message to [@cph_ex](https://twitter.com/cph_ex)

* * *
At this meet up we will do a pair programming exercise, so bring your laptop with Elixir and Phoenix installed—help with the installation can be found in the Phoenix Documentation: http://www.phoenixframework.org/docs/installation (we can help too, no worries)

The suggested pair programming exercise can be found here: https://github.com/cphex/pwiki_workshop

We will attempt to build a Wiki server using Phoenix. Don't worry if that sounds like a mouthful, the most important thing is to have fun and learn stuff!

* * *
<strike>We can do the pair/mob programming challenge I suggested for the January meet up—not many people attended that meet up so it was more of a conversation/discussion about the BEAM platform—well, it is here if you want to check it out: https://github.com/cphex/pwiki_workshop</strike>

<strike>Any suggestions, any remarks?</strike>

<strike>Also, we need a venue. One with a projector, room for people to sit with their laptops.</strike>

**Comment by Hanspagh** [comment]
Sounds interesting, might take more than one evening though

**Comment by gausby** [comment]
@Hanspagh It might be a bit ambitious, but I think it would still have value—poking around with Phoenix and Elixir—even if we don't get to complete the task during the meet up.

**Comment by gausby** [comment]
I've updated the issue description with location and a description of the event. Be sure to tweet about the event, and tell all your friends who could be interested in learning a bit about Elixir and Phoenix.

**Comment by madsflensted** [comment]
It will be fun!

**Comment by niklasni1** [comment]
Calendared. See ewes.

**Comment by skovsgaard** [comment]
I checked for it literally a minute before seeing we're being hosted by Prosa, so I may have a venue for March.

Sorry about being this late on it.

**Comment by gausby** [comment]
@skovsgaard cool. Great work!

**Comment by olegam** [comment]
Looking very much forward to get my hands dirty with some Elixir tonight! @gausby do you know if there will be some food/snacks or we should eat before going?

**Comment by valberg** [comment]
@olegam There will be no food/snacks - unless you bring them yourself :smile:

**Comment by olegam** [comment]
@valberg Thanks.

**Comment by gausby** [comment]
It would be lovely if we could provide snacks, but unfortunately we have no sponsors for that :)

Prosa has coffee though!

**Comment by olegam** [comment]
Coffee is absolutely fine:) I'm well fed now so I should be able to keep concentration up

**Comment by gausby** [comment]
Thank you for a fantastic meet up. I hope that everyone learned a bit more about Elixir and Phoenix, and had fun doing so. The next meet up is already being planned in issue #37
