### ISSUE TITLE
Copenhagen Elixir and Erlang Meet Up, March 2016

### ISSUE THREAD

**Issue by skovsgaard** [cphex/cphex#37]
**Date and time:** March 22, 18h00
**Location:**
>**Lokalebasen**
>Æbeløgade 4, 1.
>2100 København Ø
[Map link](https://www.google.com/maps/place/Lokalebasen.dk/@55.7112585,12.5620186,17z/data=!4m6!1m3!3m2!1s0x4652525ed39afd6f:0x23b8f2c302383c53!2sLokalebasen.dk!3m1!1s0x4652525ed39afd6f:0x23b8f2c302383c53?hl=en)

~~I may or may not have a venue, which I will check up on as soon as possible. If that works out it will be a place with no projector and just a large TV, so while it would be possible to do talks, it'd be more suited for working on something.~~

I checked it out here and we're go for hosting it. If anyone has talks or anything we do have a big enough TV, but the ideal would be something like our usual thing with exercises.

If people are still interested in continuing the pair programming task from last time (https://github.com/cphex/pwiki_workshop) we can do that or if anyone has other ideas which fit in the time frame of a single night, please just comment here. Likewise if you have an idea for a talk or something you want to demonstrate, just comment here.

**Comment by valberg** [comment]
@skovsgaard I have two venues up my sleeve if your venue doesn't pan out :smile:

**Comment by skovsgaard** [comment]
That's perfect. I'll get back to you soon as I've checked here.

**Comment by skovsgaard** [comment]
Venue is Lokalebasen. Does anyone have any cool ideas for things to work on or would it be fine to just continue on the wiki project?

**Comment by gausby** [comment]
I've just created the event on meetup.com http://www.meetup.com/CPHEX-Copenhagen-Elixir/events/229319365/ please let me know if something should be changed.

Also, send me tweets that should be send via the cph_ex twitter account.

**Comment by skovsgaard** [comment]
Getting in info in case the front door's locked: The entrance has a doorbell which should have Lokalebasen's name on it.

**Comment by skovsgaard** [comment]
The April meetup is underway and being planned in #38!
