### ISSUE TITLE
Copenhagen Elixir and Erlang Meet Up, April 2016

### ISSUE THREAD

**Issue by skovsgaard** [cphex/cphex#38]
**Date and time:** April 19th, 18h00
**Location:**

> **ShopGun**
> Arne Jacobsens Allé 16, 3.
> 2300 Copenhagen S

With the pretty limited turnout for March, we still have the [Phoenix wiki project](https://github.com/cphex/pwiki_workshop) to play with.

We're still open for talks and alternate exercises, so if you're working on something exciting or have new ideas, let us know here.

~~We need a location. Projector only necessary in case anyone has a talk ready. Otherwise it's just about the seating space.~~

---

If you have other questions and comments, this is also where to put them :)

**Comment by gausby** [comment]
I am back in Denmark.

We can do a workshop session, but my vote would probably be for a talk event. It has been a while since we have been doing talks, and while the workshops are good and we get great feedback I don't know if they put off some people when they read the description.

If we do workshop sessions we could consider implementing a LRU cache process:

> Least Recently Used (LRU)
> Discards the least recently used items first. This algorithm requires keeping track of what was used when, which is expensive if one wants to make sure the algorithm always discards the least recently used item. General implementations of this technique require keeping "age bits" for cache-lines and track the "Least Recently Used" cache-line based on age-bits. In such an implementation, every time a cache-line is used, the age of all other cache-lines changes. LRU is actually a family of caching algorithms with members including 2Q by Theodore Johnson and Dennis Shasha, and LRU/K by Pat O'Neil, Betty O'Neil and Gerhard Weikum.

—https://en.wikipedia.org/wiki/Cache_algorithms

This would require us to learn about ETS tables. Perhaps we could have a presentation on ETS before the workshop session. I would love to see peoples solution to this problem.

**Comment by skovsgaard** [comment]
I really like that exercise idea, but you're right it's been a while we've had talks. If anyone has anything they want to share, the latter would be super cool.

Also we still need a venue if anyone has or knows of a place.

**Comment by gausby** [comment]
We still need a venue for this meet up. I'll ask around!

@skovsgaard How about Lokalebasen?

**Comment by valberg** [comment]
@gausby we could do it at ShopGun?

**Comment by gausby** [comment]
@valberg awesome, if ShopGun wants to host us :)

**Comment by skovsgaard** [comment]
Should I update with ShopGun as host?

**Comment by valberg** [comment]
@gausby of course! @skovsgaard yes! go!

**Comment by madsflensted** [comment]
If you are unsettled on the topic, we could also give GraphQL a look? Seems to be some good learning resources available for Elixir/Phoenix: http://graphql-elixir.org/ http://absinthe-graphql.org/learning-graphql/

**Comment by gausby** [comment]
So, should we go with the LRU task, or should we look into GraphQL?

I guess we could do some Phoenix next month. I've been working a bit with Guardian and Überauth. I could perhaps do a presentation (next month!).

**Comment by valberg** [comment]
I'm down with playing with GraphQL - can anyone make a quick
introduction maybe?

## 

víðir

On Mon, Apr 18, 2016, at 20:13, Martin Gausby wrote:

> So, should we go with the LRU task, or should we look into GraphQL?
> I guess we could do some Phoenix next month. I've been working a bit
> with Guardian and Überauth. I could perhaps do a presentation (next
> month!).
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub[1]

Links:
1. https://github.com/cphex/cphex/issues/38#issuecomment-211508320

**Comment by gausby** [comment]
I can read up on it. I have been working on some other stuff than the web front-end, but some of the last stuff I did was to add GraphQL to the mix…no promises about the quality of my presentation, I'll do it if we are only a few ;)

**Comment by valberg** [comment]
Just a basic intro will do :) :+1:

## 

víðir

On Mon, Apr 18, 2016, at 20:27, Martin Gausby wrote:

> I can read up on it. I have been working on some other stuff than the
> web front-end, but some of the last stuff I did was to add GraphQL to
> the mix…no promises about the quality of my presentation, I'll do it
> if we are only a few ;)
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub[1]

Links:
1. https://github.com/cphex/cphex/issues/38#issuecomment-211515969

**Comment by skovsgaard** [comment]
I totally forgot to close this.

The May meetup is being planned in #41.
