### ISSUE TITLE
Copenhagen Elixir and Erlang April/May Hackday/Hackathon

### ISSUE THREAD

**Issue by gausby** [cphex/cphex#39]
**Date and time**: Saturday May 7 @ noon (around 12h)
**Location**: 

> <strong>Prosa</strong>
> Vester Farimagsgade 37A
> 1606 København V
> [map](https://www.google.com/maps/place/Vester+Farimagsgade+37A,+1606+København+V/@55.6787781,12.5626736,17z/)

Directions: The venue is pretty close to Vesterport Station and the Vester Farimagsgade bus stop. We will be sure to hang a sign on the door with contact information. If you are unable to find it try sending a twitter message to [@cph_ex](https://twitter.com/cph_ex)

---

Anyone up for an all day event; hanging around with our computers, discussing stuff and learning about Erlang, LFE and Elixir?

We would need:
- [x] A venue that will let us loiter for a day
- [x] A date for the event, are there any weekends that are better than others?
- [x] Someone who promise to be at the venue from start to finish (I, Martin Gausby, can do that, if I am available on the agreed upon date)
- [ ] maybe coordinate some food
- [x] maybe have a projector if someone wanna show something

I personally don't like 'hackathon' events where a topic and a deadline is forced upon the attentants, but I think there is value in getting together and work on individual projects, or learn about a specific topic that the individual chooses.

What should we call it? Hackathon or hackday, or picnic?

**Comment by valberg** [comment]
We can be at PROSA if it's a weekend where I'm available :smile:

**Comment by gausby** [comment]
@valberg could you list the weekends you/prosa are available ? :)

**Comment by valberg** [comment]
@gausby What about Saturday the 23rd of April?

**Comment by gausby** [comment]
23rd could work, but it is after a holiday (I think store bededag is a holiday) so many might use the extended weekend to be with family or travel.

**Comment by gausby** [comment]
We have been talking about May 7 on our IRC-chan (#cphex on freenode)

**Comment by valberg** [comment]
@gausby should we go with that one and get the event organised/published? I also have to book PROSA (just wrote them) :)

**Comment by gausby** [comment]
@valberg yeah, let's pick May 7 if we can get a venue for that day.

**Comment by gausby** [comment]
Okay, I'll update the issue with the location; PROSA, and the date.

**Comment by codella** [comment]
@gausby @valberg I can give a 5-10 minutes tech talk around exit signals tomorrow. I have prepared 6 slides and I have some more code to show after the talk, if people are interested.

I also wrote [here](https://github.com/cphex/cphex/issues/41#issuecomment-217406004) because was unsure where to. Sorry for the noise :^)

**Comment by gausby** [comment]
@codella Don't be sorry. That is fantastic. You can present it tomorrow and we can discuss it, and then you can reuse the presentation at one of our regular meet ups to a perhaps larger audience and with the added information that will result from our discussion afterwards. How does that sound?

**Comment by valberg** [comment]
@codella Sounds awesome to me! :D Looking forward to it!

**Comment by codella** [comment]
@gausby feedback is one of the things I expect to have from a good meet up :^)

**Comment by gausby** [comment]
Closing this one. Thanks to everyone who showed up.
