### ISSUE TITLE
Creating Beam/Elixir/Erlang/OTP visualisations in Elm event

### ISSUE THREAD

**Issue by gausby** [cphex/cphex#40]
I've been thinking about how to make Elixir and Erlang more presentable and accessible to a wider audience. One of the ideas that makes the most sense to me is visualisations of the CS principles that we deal with at the meet ups.

I for one admit that I understand a sorting algorithm quicker if I see it visualised like this: https://www.youtube.com/watch?v=kPRA0W1kECg (**bevare, I don't know if that link is good for people suffering from epilepsy**)

We have an overlap of members who also go to the Elm meet up. I think that it could be interesting to do a meet up where we talk about the Beam/Elixir/Erlang/OTP principles and attempt to visualise them using Elm. These visualisations could potentially be used in futur presentations.

**Comment by madsflensted** [comment]
Interesting. What OTP principle would you start with? And what would be a possible visualization?

**Comment by gausby** [comment]
I have an idea of implementing a visualisation of a worker scheduler to show the difference between how the node.js/js scheduler work and how the Beam differes. This is an idea that I've had for a talk I wanted to give at CopenhagenJS but have been too afraid to actually prepare and give ;)

Other interesting visualisations could be a graph; supervison; message parsing.

**Comment by madsflensted** [comment]
Yes - "seeing" different distributed algorithms at work. 

Maybe it would be possible to combine a "message dying approach" with some sampling of the messages in certain process queues, with the goal of being able to visualize message flows for already implemented algorithms.

**Comment by skovsgaard** [comment]
I'd absolutely be up for this, but I can't think of anything I know well enough to visualize. I assume a graph of distributed nodes isn't really BEAM-specific enough.

**Comment by gausby** [comment]
Doesn't have to be beam specific.

And it is okay to not know everything, that is why we get together and discuss and learn about the topic. I for one doesn't know it all, and in some places I just have an intuition that I assume to be correct—which is alway nice to get corrected.

**Comment by gausby** [comment]
@madsflensted you mean for visualizing a sorting algorithm?

**Comment by gausby** [comment]
@madsflensted sorry. I can't read. And this iOS github client doesn't work. :)

I would like to meet in person and hear more about that idea!

**Comment by gausby** [comment]
Some visualisations of CS stuff I like:
- RabbitMQ visualizer https://jmcle.github.io/rabbitmq-visualizer/
- [Everything on the red blob games blog](http://www.redblobgames.com)!
