### ISSUE TITLE
Copenhagen Elixir and Erlang Meet Up, May 2016

### ISSUE THREAD

**Issue by gausby** [cphex/cphex#41]
## Event

**Date and time**: Monday, May 23rd @ 18h
**Location**:

> **ShopGun**
> Arne Jacobsens Allé 16, 3.
> 2300 Copenhagen S
> [Map](https://goo.gl/maps/GXS0K)

---
## Agenda

Jonas will give an introduction to LFE, Lisp Flavoured Erlang. After that we will do a pair programming exercise where we get to play with LFE or any of the other languages on the Erlang Virtual Machine.

---

We need to find or decide upon:
- [x] a date (and time) for the meet up
- [x] a location
- [x] whether or not to have talks or an group assignment

**Comment by gausby** [comment]
We have done really good for some time, but I think we are slowing down in getting new members and having people returning to future meet ups.

I know that no specific day will be better than others, we will always have conflicts with other meet up groups—the day where we had a meet up on the same day as Copenhagen Docker and Funktionelle Københavnere was brutal—but some people might have other obligations on Tuesdays. _I suggest that we try the third monday of May_, that might allow some people who has obligations on Tuesdays a chance to join a meeting.

And while I personally enjoy the group assignments/tasks, and I truly think they are the most inclusive for newcomers to the platform, I still fear it might put off some people because it sound like «work». As my eight year old nephew told me when I wanted to show him something cool he can do with numbers: «I am not at school right now!»

On a final remark, are there any ideas to what we can do to get a broader audience? _I guess going to other meet ups and giving presentations about Elixir could help, as long as it is not hostile._

**Comment by codella** [comment]
Hi,
not sure if I am going off-topic, but if people ran out of ideas for a talk then cherrypicking from the various articles linked in the [Plataformatec weekly news letters](http://plataformatec.com.br/elixir-radar) and preparing talks about the most interesting/relevant ones could be a bit of a help!

Just some examples:
- [Debugging techniques in Elixir](http://blog.plataformatec.com.br/2016/04/debugging-techniques-in-elixir-lang/?utm_campaign=elixir_radar_45&utm_medium=email&utm_source=RD+Station)
- [Railway development in Elixir using `with`](http://scottmessinger.com/2016/03/25/railway-development-in-elixir-using-with/?utm_campaign=elixir_radar_44&utm_medium=email&utm_source=RD+Station)
- [Fuzzy String Matching](https://medium.com/@pjhampton/fuzzy-string-matching-in-elixir-f84ba6e1f0ec#.oaiymvyg5)

I realise that probably for many of you the content of these articles is basic, but I thought that writing down the idea was worth a shot ;^)

**Comment by gausby** [comment]
@codella I know that I personally build up some bad habits from time to time, and I am sure others do the same. I think it would be good for the meet up if we had some basic talks—I think that the experts in the group enjoy these too and they often have insightful comments.

I would like to know more about debugging techniques myself…I often find myself resort to `IO.inspect/1` when I could have used Pry or `:debugger`. I would also like to know about basic process tracing and such :)

**Comment by codella** [comment]
@gausby if the organisers agree, we could try to give one tech talk of this kind and then spend the rest of the time on a group assignment?

Btw, I think I can help on May's meetup, if anything is needed!

**Comment by gausby** [comment]
@codella I think that it would be great. One talk and then a workshop.

I guess the workshop could include:
- Using Pry
- Step debugging with `:debugger`
- Using `:observer.start` to monitor and inspect a running application
- Tracing a process

…and yes, if you have time and energy your help would be highly appreciated. I think that some new perspectives and ideas would be great, and people to ping-pong with would surly provide that :)

**Comment by codella** [comment]
>  I think that some new perspectives and ideas would be great, and people to ping-pong with would surly provide that :)

Likewise! :^)

**Comment by codella** [comment]
@gausby @skovsgaard I think this article can be a good topic to propose as a flash talk too: [Understanding Exit Signals in Erlang/Elixir](http://crypt.codemancers.com/posts/2016-01-24-understanding-exit-signals-in-erlang-slash-elixir/?utm_campaign=elixir_radar_41&utm_medium=email&utm_source=RD+Station).

I can also help preparing some material around debugging, as @gausby suggested!

**Comment by codella** [comment]
@gausby I can give a 5-10 minutes tech talk around exit signals tomorrow. I have prepared 6 slides and I have some more code to show after the talk, if people are interested.

**Comment by gausby** [comment]
So, should we schedule this meet up for Monday 16th?

(I answered Condella in the hackathon thread)

Also we need to think about a venue for this meet up.

**Comment by gausby** [comment]
I suggest that we move this meet up one week. What do you think of having this meet up Monday 23rd?

**Comment by gausby** [comment]
@codella We might have Jonas giving a talk about LFE. Did you want to give a talk too?

**Comment by codella** [comment]
@gausby I haven't planned any talk yet :( looking forward to Jonas' talk though :)

**Comment by gausby** [comment]
@codella Fair enough :). We could do a group assignment in LFE after Jonas' talk.

**Comment by gausby** [comment]
@skovsgaard are you okay with me putting your LFE talk on the agenda?

**Comment by skovsgaard** [comment]
Sure, just put it on there. I'll see what I can put together.

**Comment by gausby** [comment]
Thanks to everyone who showed up. The signups on meetup.com looked very dismal for this meet up, but we had 6 members showing up, and great discussions were had. I don't think meetup.com has proven itself as a trustworthy source when anticipating how many will actually show up.

**Comment by skovsgaard** [comment]
Cool. Thanks to everyone who did show up. The June meetup is being planned in #42.
