### ISSUE TITLE
Copenhagen Elixir and Erlang Meet Up, June 2016

### ISSUE THREAD

**Issue by gausby** [cphex/cphex#42]
Time and date: Monday, June 13th. @ 18:00
Location (new venue):

> Quantads
> Torvegade 29,
> 1400 København
> [Map](https://www.google.dk/maps/place/QuantAds/@55.6777385,12.5810979,15z/data=!4m5!3m4!1s0x0000000000000000:0xfa5c26de4bcf9721!8m2!3d55.6731359!4d12.5903535)

Please message @[cph_ex](https://twitter.com/cph_ex) on Twitter if you need directions.
## Agenda

We have some friends visiting, and they have agreed to give some talks;
- [Kamil Lelonek](https://twitter.com/KamilLelonek) - The basics of Metaprogramming in Elixir
- [Michał Załęcki](https://twitter.com/MichalZalecki) - Reactive WebSockets with Phoenix channels

---

Please come forward if you can host and/or sponsor food. It will be a great one. We will need a room with a projector, hopefully we will be around a dozen at this meet up.

**Comment by prognostikos** [comment]
I may be able to arrange a location for Monday if this is still happening @gausby.

**Comment by gausby** [comment]
@prognostikos The event is still on. We have a backup venue up our sleeve, but it is kinda hard to get to (actually people got lost last time we had an event there)—so we are very much interested in a more accessible venue :)

**Comment by prognostikos** [comment]
Cool, I'm making inquiries (may not get a response until Monday morning, unfortunately). If it works out it would be Rainmaking Loft by the Opera.

**Comment by gausby** [comment]
@prognostikos Fantastic. I'll tweet out that we will announce the venue tomorrow. Thank you very much.

**Comment by gausby** [comment]
@prognostikos any news?

**Comment by prognostikos** [comment]
@gausby yes, but not great news, unfortunately. It won't be possible to do it at the Loft tonight as I won't be able to stay until the end of the event and don't have anyone else to handle closing up, etc. Sorry - one of these Mondays _will_ work out.

**Comment by gausby** [comment]
Thanks for the heads up, Matt. We'll go with the backup venue then. It's a bit hard to get there but we got a plan of meeting at the near by train station and walk to the venue from there.

I hope that we will be better at securing venues in the future.

**Comment by naruvimama** [comment]
Hey Martin,

We would be able to host it at Quantads. It is in Christianshavn so is pretty central :)
Torvegade 29, 1400 København
Call me to let you in : 53 58 86 22

https://goo.gl/maps/mpnVCHY8jxq­

**Comment by gausby** [comment]
@naruvimama sorry, I already communicated the backup venue. The plan is to meet at Nordhavn Station around 17:50, wait there for a bit for people to arrive and walk to the venue.

I think it will be confusing to all the people who just received a bunch of notifications if I change it now.

**Comment by Hanspagh** [comment]
Maybe we could make a map, so people know which way to go?

**Comment by gausby** [comment]
@Hanspagh excellent idea. Coming right up!

**Comment by KamilLelonek** [comment]
![image](https://cloud.githubusercontent.com/assets/3199333/16006021/ef9a151e-316a-11e6-8fd1-ff34e2a22c18.png)

**Comment by gausby** [comment]
@KamilLelonek That is not the shortest/easiest route! :-O

**Comment by KamilLelonek** [comment]
It is ;) Everywhere else is a big construction right now and the other ways are closed.

I'll pick you from Nordhavn and I'll go with you through a shortcut (that requires magnetic card) but those who are late will need to follow this map.

**Comment by gausby** [comment]
okay, change of plans, @naruvimama I'll give you a call!

**Comment by naruvimama** [comment]
You can ring the buzzer to be let in

I can also be reached at 53 58 86 22

**Comment by gausby** [comment]
I've decided to move the event to QuantAds. The address is in the issue description and has been updated on meetup as well as tweeted out here: https://twitter.com/cph_ex/status/742325811064213504 (be sure to retweet that to make sure the word is spread)

Even though this create some confusion I think it is better to move the venue, and communicate this, than having to walk/bike more than 2 km to and from the venue.

**Comment by KamilLelonek** [comment]
Here come my slides: https://twitter.com/KamilLelonek/status/742611644640022528
