### ISSUE TITLE
Copenhagen Elixir and Erlang Meet Up, July 2016

### ISSUE THREAD

**Issue by gausby** [cphex/cphex#43]
Time and date: July 19th, time: 18h00
**Location**: 

> <strong>Prosa</strong>
> Vester Farimagsgade 37A
> 1606 København V
> [map](https://www.google.com/maps/place/Vester+Farimagsgade+37A,+1606+København+V/@55.6787781,12.5626736,17z/)

Directions: The venue is pretty close to Vesterport Station and the Vester Farimagsgade bus stop. We will be sure to hang a sign on the door with contact information. If you are unable to find it try sending a twitter message to [@cph_ex](https://twitter.com/cph_ex)

---

We need to find and decide upon:
- [x] a venue
- [x] a date
- [x] a time
- [ ] food/drink/snacks available: <YES/NO>

**Comment by gausby** [comment]
I got some requests for a hands on session after the last meet up, so I suggest that we consider that format for this meet up.

**Comment by KamilLelonek** [comment]
Idea: let's do something we did last year: https://github.com/cphex/cphex/issues/28

**Comment by gausby** [comment]
@KamilLelonek exact same exercise or some new?

**Comment by KamilLelonek** [comment]
A new one would be better.

**Comment by gausby** [comment]
Idea for a team work exercise, either mob- or pair programming: Implement the logic for a Cards Against Humanity clone, called Processes Against Humanity.

**Comment by gausby** [comment]
I will set the date of the meet up to July 18th. We will go with that unless we get a really good venue for another date.

**Comment by gausby** [comment]
I've changed the date to July 19; and added Prosa as a venue.

**Comment by gausby** [comment]
Thanks for joining this meet up. We had around 7 people showing up, and amongst them some newcomers who had no experience with Elixir or functional programming. We worked on the Enum workshop to get everyone up to speed with recursion and pattern matching. Personally I think it was great even though we had a slow start with technical problems.

Thanks to PROSA for hosting the meet up. We are already planning the next meet up.
