### ISSUE TITLE
Copenhagen Elixir and Erlang Meet Up, August 2016

### ISSUE THREAD

**Issue by gausby** [cphex/cphex#44]
Time and date: Monday, August 29, time: 19h00
Location:

> Lokalebasen
> Æbeløgade 4
> 2100 København
> [Google Maps link](https://www.google.com/maps/place/Lokalebasen.dk/@55.711246,12.5637142)

---

Please submit ideas for this meet up in the comments.

**Comment by gausby** [comment]
I will be giving a talk at Erlang User Conference on September 8th, so I would like to take the opportunity to practice my talk in front of a live audience, if you are willing to lend me your time and your ears, etc.

So I suggest that we are doing a talk session for this meet up—Don't be a stranger if you have a talk you wanna give yourself.

**Comment by skovsgaard** [comment]
Did anyone suggest a venue? I might have one unless last time was an indication that it's too far away (or I give terrible directions).

**Comment by gausby** [comment]
@skovsgaard Where is this?

**Comment by skovsgaard** [comment]
If they're okay with hosting us\* even if we're slightly more people than last time, it'd be Æbeløgade 4 on Østerbro. Pretty close to Ryparken station.

\* update: It's fine if we wanna do the meetup here.

**Comment by gausby** [comment]
Perfect, Ryparken is not that far away, and there is a train connection to Nørreport Station.

**Comment by skovsgaard** [comment]
Also from Nørreport are buses 150s, 184 and 185 which all have the stop, Haraldsgade, which is even closer by here.

Assuming it's settled, I added the location to the top of this issue.

**Comment by skovsgaard** [comment]
Are we going with 1800h as per usual?

**Comment by gausby** [comment]
Let's say 19h00 if we can. We are going to have one talk (unless there are more people who want to give one), so I don't think it will get that late.

**Comment by skovsgaard** [comment]
That's fine. Let's go with 19h.

**Comment by gausby** [comment]
@skovsgaard how about postponing the meet up to next week? I was a bit late with the promotion so if we postpone it perhaps more than two people will get to know about the event.

**Comment by skovsgaard** [comment]
That's a really good idea. Let's postpone.

**Comment by gausby** [comment]
Will Lokalebasen be able to host next week?

**Comment by skovsgaard** [comment]
I can't check it right now, but I'll get back with an answer today.

**Comment by skovsgaard** [comment]
Update: Monday the 29th is fine here. So we'll keep Lokalebasen as venue.

**Comment by skovsgaard** [comment]
Are we still doing 19h or earlier?

**Comment by gausby** [comment]
Yeah, still 19h; why?

**Comment by skovsgaard** [comment]
It's fine. Earlier would've been easier for me seeing as I'm here all day, but it'd be silly to change time now. 19h it is.

**Comment by niklasnisbeth** [comment]
Jeg kan desværre ikke være der i aften, forhåbentlig næste gang.

**Comment by gausby** [comment]
@skovsgaard yeah; from what I've learned now would be too late to change our minds on details like that. Would require too much communication and we wouldn't reach all…

**Comment by skovsgaard** [comment]
@niklasni1, det er bare i orden. Vi ses næste gang.

@gausby, you're absolutely right. Times with last minute changes have yielded weird results. Let's just keep it at 19.
