### ISSUE TITLE
Copenhagen Elixir and Erlang Meet Up, October 2016

### ISSUE THREAD

**Issue by gausby** [cphex/cphex#46]
**Date and time**: Thursday 20, @ 19:00 (the 2 year anniversary of our first meet up)
**Venue**: 

> Paludan Bog & Café
> Fiolestræde 10-12 
> Denmark
> [Map](https://www.google.dk/maps/place/Paludan+Bog+%26+Caf%C3%A9/@55.680363,12.5710738,17z/data=!3m1!4b1!4m5!3m4!1s0x465253103fe19c97:0xdcf4e0b8fae25688!8m2!3d55.680363!4d12.5732625)

**Agenda**: Social gathering, ask questions about OTP, Elixir and Erlang.

---

We need to find and decide upon:
- [x] a venue
- [x] a date
- [x] a time
- [ ] <strike>whether food/drink/snacks are available or if we pool our cash and send out for take away</strike>

**Comment by gausby** [comment]
I suggest that we do this meet up Thursday, 20th.

The 20th of October will be the 2 year anniversary of the first meet up we ever did.

**Comment by gausby** [comment]
Should we do a classical cafe meet up, or should we do a workshop?

**Comment by skovsgaard** [comment]
I have been a bit short on ideas lately, but the café thing sounds nice and reminiscent of the first meetup. It does depend on how many we are though. Are you thinking Paludan or somewhere else?

**Comment by gausby** [comment]
It will be short notice (classical CphEx), so I guess we will be few. Paludan would perhaps work, it has been a while since I've been there so I don't know how many go there on  a Thursday evening at this time of the year.

**Comment by skovsgaard** [comment]
We can try it out and see? Do we have anything for the agenda?

**Comment by gausby** [comment]
I've just announced the meet up on meetup dot com: https://www.meetup.com/CPHEX-Copenhagen-Elixir/events/234922994/

@skovsgaard if we are going to do a social gathering at Paludan I don't know if we need an agenda; we can just talk and answer questions—we are so much better at that now than we were 2 years ago ^_^

**Comment by skovsgaard** [comment]
You're right. I'm not really sure what to put on it that would fit with the cafe setup either. Let's stick to talk and questions, then.

**Comment by gausby** [comment]
I'll update the event info and set Paludan as the venue.
