### ISSUE TITLE
Elixir and Ember.js Evening

### ISSUE THREAD

**Issue by gausby** [cphex/cphex#47]
<strong>[There will be food and drinks, so please sign up on FooCafe's page if you want to attend!](http://www.foocafe.org/copenhagen/events/1283-lauren-tan-sugarpirate-is-coming-to-town)</strong>

Date: November 3rd, at 17:30h to 20:00h
Location:

> Foo Café 
> NOHO 
> Flæsketorvet 28 
> 1711 Copenhagen V
> [Map](https://goo.gl/maps/nLkZDqQT5to)
## Talks:
- An introduction to Elixir geared towards JS developers—by Martin Gausby
- <strike>Ember and Phoenix—by Olle Jonsson</strike>
- (you?, please write in the comments—should be geared towards people interested in Elixir, Ember or both)

---

Lauren Tan is going to visit Copenhagen in the beginning of November ([3rd to 5th](https://twitter.com/sugarpirate_/status/779810859027619840))

<strike>It would be a great opportunity to do a joint Elixir (with Phoenix) and Ember meet up. I (Martin Gausby) could do an introduction to Elixir geared towards JavaScript developers—I've done some JS in the past—and if someone could follow that with an Phoenix+Ember talk it would be amazing.

Further more, I think we should try putting this together with Foo Cafe, who has a location in Kødbyen, central Copenhagen.</strike>

Any thoughts?

**Comment by skovsgaard** [comment]
:+1: for the theme; great idea, but I don't think I have anything to contribute knowing absolutely nothing about Ember. Maybe we could ask in a tweet from the cphex account if anyone has any experience with that combo?

**Comment by mike-north** [comment]
I'll be a short flight away in the UK for http://bris.tech/. Would love to stop by for something like this, providing the times don't clash

**Comment by gausby** [comment]
@mike-north I will push for November 3rd as it is a Thursday. I don't think a meet up on a Friday would be successful. 7 p.m. is usually a good time to meet here as most people eat around 6 p.m. Hope it doesn't clash :)

@skovsgaard I try to find some Ember people!

**Comment by olleolleolle** [comment]
I'm an Ember.js user, and an Elixir fan.

**Comment by gausby** [comment]
@olleolleolle fantastic, do you have experience working with Phoenix Channels from Ember, and do you want to present it? :)

**Comment by olleolleolle** [comment]
@gausby Not yet! Sounds like something to be trying!

**Comment by gausby** [comment]
@olleolleolle let me know if you want to show something. No pressure ^_^

**Comment by olleolleolle** [comment]
@gausby It sounds _quite_ relevant to my interests (Example walkthrough: http://www.programwitherik.com/how-to-guide-the-phoenix-framework-and-ember-js-2/ )

[Example Channels solution in Phoenix, without Ember.js](https://github.com/chrismccord/phoenix_chat_example)

[Phoenix docs on Channels](http://www.phoenixframework.org/docs/channels)

**Comment by gausby** [comment]
I've tried to put an event description together, and ended up with this:

«A friend of both the Elixir/Phoenix and the Ember community is visiting our city, and on that occation we want to invite everyone who has an interest in either of the technologies to join us for an evening dedicated to both. We will start out with an introduction to Elixir geared towards JavaScript developers discussing why you should consider a Phoenix backend for your next project; and then a talk about Phoenix as a backend for an Ember application.»

What do you think? Please correct my english—I won't get mad—it is not my first language…and should I add anything?

**Comment by Hanspagh** [comment]
Maybe we should mention who the friend is :)
Something like

> Lauren Tan, a friend of both the Elixir/Phoenix and the Ember community is visiting our city

**Comment by gausby** [comment]
@Hanspagh Perhaps; But I should ask her if she want that kind of exposure.

**Comment by gausby** [comment]
I got some feedback on the text from foo cafe. They say: _Could you give us a bit more on 'Phoenix as a backend...'? Some benefits and drawbacks, if there are any? Give people an idea of what they will learn._

I am busy at work right now, and I don't have that much experience with Ember (if any), so please write some good arguments for using Phoenix for Ember :) (the obvious ones are channels, scalability as well as availability)

**Comment by gausby** [comment]
@olleolleolle Would you be interested in giving a presentation?

**Comment by olleolleolle** [comment]
@gausby I want to give a presentation on Ember.js and Elixir!

**Comment by gausby** [comment]
@olleolleolle I'll put you on the agenda then; do you have a title for the presentation?

**Comment by olleolleolle** [comment]
@gausby No, not yet, but it'll be on the theme "I'm using Ember.js with Ruby everyday, how does it feel using with Phoenix"?

**Comment by gausby** [comment]
@olleolleolle cool, just ping me when/if you want me to change the title :)

**Comment by gausby** [comment]
Foo Café posted the event to their Facebook page, please sign up if you are interested in going, and share with your network: https://www.facebook.com/events/529149493957914/

**Comment by skovsgaard** [comment]
Is there a place we can sign up if we're not on Facebook?

**Comment by codella** [comment]
@gausby I have a few slides ready on an overview of the Erlang scheduler - not sure that'll fit in this time :)

**Comment by gausby** [comment]
@codella I am going to touch on preemptive scheduler vs an event loop in my presentation; at least I wrote that down when I brainstormed earlier :)

**Comment by codella** [comment]
@gausby sounds like you have enough of scheduling already xD

**Comment by mike-north** [comment]
If you guys want to steer people toward an Ember/Phoenix tutorial, [here's the multi-part one that I've been progressively building](https://medium.com/peep-stack/building-a-performant-web-app-with-ember-fastboot-and-phoenix-part-1-fa1241654308)

**Comment by olleolleolle** [comment]
**I CAN'T COME.**😿 😿 😿 😿 😿 😿 😿 😿 😿 😿 

I caught a cold, and need to sleep. 

I hope you'll have fun!

**Comment by gausby** [comment]
@olleolleolle oh my, I don't have any Ember in my presentation (and I don't know anything about it)…I'll improvise—god bedring.

**Comment by gausby** [comment]
Thanks for a great meet up. It seems that it sparked some interest for Elixir…we've seen some new members joining the meet up group, so hopefully we will see some new faces at the workshop events. 

I think collaborating with FooCafe was nice, and I have a feeling that it will only get better if we continue doing that.
