### ISSUE TITLE
Copenhagen Elixir and Erlang Meet Up, December 2016

### ISSUE THREAD

**Issue by gausby** [cphex/cphex#48]
**Date and time**: December 13, 18h30
**Venue**: 

> Rocket Labs Aps
> Hejrevej 30
> 2400 Nørrebro
> [Map](https://www.google.dk/maps/place/Hejrevej+30,+2400+København+NV/@55.6997357,12.5303271,16.64z/data=!4m5!3m4!1s0x4652524af0d917c1:0xacc2c984746faa66!8m2!3d55.699662!4d12.532918)

**Agenda**: Social gathering, ask questions about OTP, Elixir and Erlang.

---

We need to find and decide upon:
- [x] a venue
- [x] a date
- [x] a time
- [ ] food/drink/snacks

**Comment by gausby** [comment]
I am a bit late with the planning and marketing of this event, how about moving it to Monday next week? We will not clash with Funktionelle Københavnere; they are on at Tuesday.

I am thinking about making it a workshop event.

**Comment by skovsgaard** [comment]
I think it'd be a good idea, moving it. What would the workshop entail? Or what would we be doing?

**Comment by srbaker** [comment]
Heya, I found the CPHEX group because I'm planning to build part of foocafe.org using Phoenix and wanted to see if there were local folks (I'm in Malmö) interested in Elixir and Phoenix.

Conveniently, FooCafé was started to provide "a conference every day", and is just getting started in Copenhagen. I'd love for CPHEX to be hosted by FooCafé. We'd handle all of the logistics like venue, food/drink sponsor; all you have to do is coordinate a date and provide a speaker. We'll  provide announcement and event registration via our website, find sponsors, and handle everything. Literally all you have to do is agree on a date, provide a speaker, and show up. (We can even help with the finding speakers bit.)

We won't hijack your event, we just want a place for people to go to learn and share experiences. FooCafé is very attendee focused. Sometimes a sponsor will want to say "hey, we're hiring" in addition to paying for the food, but they won't talk longer than 3 minutes.

All you have to do is pick dates, and provide speakers. We'd do the rest.

Thoughts?

**Comment by gausby** [comment]
@srbaker I like the idea; we even did a meet up in collaboration with foocafe on November 3 <a href="https://twitter.com/cph_ex/status/794289869526880256">:)</a>

Do you think foocafe would be ready for an event Monday? I consider making it an hands-on session, so people should bring their laptops…it's the best way of learning this stuff as it is a bit complex and there's a ton to digest.

**Comment by gausby** [comment]
@skovsgaard I guess basic stuff; maybe phoenix ?

As much as I like to talk about processes and supervision I guess Phoenix expose just enough to show some concepts, and make the attendants feel like they produce something that works.

**Comment by skovsgaard** [comment]
@gausby, that's fair enough. Maybe we can use it as a stepping stone to - at a later time - doing a Plug workshop or something to make it more OTP-ish.

**Comment by skovsgaard** [comment]
Is this being superceded by the cafe thing today or are we doing both?

**Comment by gausby** [comment]
@skovsgaard I plan on doing both, the cafe thing today is because Lenz is in town and I haven't had time preparing a bigger thing.

**Comment by skovsgaard** [comment]
Both sounds like a plan.

**Comment by gausby** [comment]
@skovsgaard about the plug workshop, could be an idea, but there is no guarantee that the people showing up will return for another meeting or workshop, so just prepare it with no priorer Elixir/Phoenix knowledge in mind. I know it is kind of a sad realisation, but I think it is in alignment with reality.

**Comment by skovsgaard** [comment]
Well, I guess it wouldn't have to be in a Part1/Part2 format for it to work. We could do something Phoenix-focused this time and Plug at a later meetup. And the only bonus for people showing up both times is that they get a slightly better understanding of how Phoenix works rather than just how to make it do stuff.

But I agree. The sad but pragmatic choice is Phoenix.

**Comment by gausby** [comment]
I've been thinking about this: considering that I haven't gotten around to announcing it on meetup.com, and that we have already had two meet ups in November; let's move this meet up to the first or second week of December. The latter part of December is always busy anyways, so this makes sense to me.

**Comment by skovsgaard** [comment]
That does make sense. So instead of doing one late-notice one this month and another possibly-low-attendance one at the end of December, we'd have one early December?

**Comment by gausby** [comment]
@skovsgaard yes, that was what I tried to communicate. Early December, first or second week. Perhaps the second week is best.

**Comment by skovsgaard** [comment]
Either works for me. Second gives more time to announce it so yeah, that's probably better.

**Comment by skovsgaard** [comment]
In the interest of finding a date: Is the 13th too late in the month?

**Comment by gausby** [comment]
I think that I has to be on the 13th. I'll add it as the date and let's start looking for a venue. I got a back up if all else fails.

**Comment by gausby** [comment]
I've just announced this meet up on the dreaded meetup.com-page, December 13 @ 18:30

  * https://www.meetup.com/CPHEX-Copenhagen-Elixir/events/236068141/

We still need a venue. (I am sure I can host it at shopgun, but I guess a venue closer to the city center would be preferable)

**Comment by hnrkptrsn** [comment]
Hi, 

I work for Motosumo and we are located at Rocket Labs - Cph NV - we could host the event if you are interested.  The place is a coworking space - probably there would be one or two interested joining from here as well.

Best, Henrik

**Comment by Hanspagh** [comment]
We would also be happy to host it at spilhuset on Pilestræde, if everything else fails 😊

**Comment by gausby** [comment]
I think that Rocket Labs would be awesome. I've been there once and I as far as I recall there is ample of space for people to sit with their laptops and do pair programming. @hnrkptrsn if you give me the address I can add it to the event description and announce it on meetup.com

@Hanspagh let's have the January meet up at Spilhuset.

**Comment by hnrkptrsn** [comment]
Sounds great - we will be looking forward to it.

Rocket Labs Aps
Hejrevej 30
2400 Nørrebro

**Comment by gausby** [comment]
@hnrkptrsn Awesome, I've updated the event description with the address. Thanks!

**Comment by gausby** [comment]
@hnrkptrsn I will use some of the weekend to prepare for the meet up, and since you are new to the meet up and bringing some extra people along: what level are you and your friends at? What do you want to know about?

**Comment by hnrkptrsn** [comment]
I guess we are fairly novice with Erlang - as we are not using Erlang as part of our systems. We are primarily a Python shop on the backend - and being mobile Swift and Java on the frontend.

I'm the one advocating for Erlang - thus the idea for the meetup - my friends are new to ecosystem.

I will prepare something showing how Erlang and Python (using ports) could play together - as this probably is a likely use case for us.

And I'm especially interested in hearing about Erlang / Elixir in production, deployment etc. experiences good/bad/etc.

**Comment by gausby** [comment]
Still not many sign ups—I would love to hear your presentation about Erlang ports :)

I don't think I will prepare a grand presentation for this event. I hope you will find it okay if I just connect my laptop to a projector, show stuff in my editor and answer questions.

Normally a few extra people show up without signing up on meetup.com, so I guess we will be around 6 or 8 people (gut feeling)

**Comment by hnrkptrsn** [comment]
I guessed mid December would be hit or miss anyway. We could postpone till January - if you feel the turnout will be better? 

I'm still on though and will do the presentation here anyway.

**Comment by gausby** [comment]
@hnrkptrsn the event is on :) Meet ups with few people have different qualities than ones with many—few people are great for Q&As and show and tells.

**Comment by skovsgaard** [comment]
Thanks, @hnrkptrsn, for hosting!
