### ISSUE TITLE
Copenhagen Elixir and Erlang Meet Up, January 2017

### ISSUE THREAD

**Issue by gausby** [cphex/cphex#49]
**Date and time**: Wednesday, Januar 18, 18h30
**Venue**: 
> **ShopGun**
> Arne Jacobsens Allé 16, 3.
> 2300 Copenhagen S
> [Map](https://goo.gl/maps/GXS0K)

---

We need to find and decide upon:

- [] What type of event: social gathering, workshop, talks ?
- [x] a venue
- [x] a date
- [x] a time
- [ ] food/drink/snacks ?

**Comment by ghost** [comment]
I think it could be Interesting to hear about what ShopGun is doing of Erlang stuff..

**Comment by gausby** [comment]
@telsgaard I don't think I have time to do slides and stuff, but I can talk to you about that :)

**Comment by ghost** [comment]
That would be cool, shall I bring something like a cake ?

Thomas
tir. 17. jan. 2017 kl. 21.28 skrev Martin Gausby <notifications@github.com>:

**Comment by gausby** [comment]
@telsgaard I don't think anyone would have anything against that :)
