### ISSUE TITLE
Copenhagen Elixir and Erlang Meet Up, February 2017

### ISSUE THREAD

**Issue by gausby** [cphex/cphex#50]
**Date and time**: Wednesday, February 22, time: 18:30
**Venue**: Falcon Social

> H. C. Andersens Blvd. 27
> 1553 København V
> [map](https://encrypted.google.com/maps/place/H.+C.+Andersens+Blvd.+27,+1553+København+V,+Denmark/@55.6741588,12.5693442,17z/data=!3m1!4b1!4m5!3m4!1s0x46525312501081b3:0x5b64f6ec07bb630!8m2!3d55.6741588!4d12.5715329)

---

We need to find and decide upon:

- [x] What type of event: social gathering, workshop, talks ?
- [x] a venue
- [x] a date
- [x] a time (is 18:30 okay?)
- [x] food/drink/snacks ?

**Comment by gausby** [comment]
I have been in contact with a company that might want to host our February meet up. If they they are still game I might suggest that we do a meet up with presentations aimed at people interested in Elixir/Erlang.

I will gladly prepare and give a presentation on Beam philosophies and how systems are designed using OTP practices.

**Comment by giulioungaretti** [comment]
@gausby  "systems are designed using OTP practices"  :heart:

**Comment by casperstorm** [comment]
Our office at Rainmaking Loft is a possibility. Let me know if the other host bails out, then ill look into it, @gausby.

Will properly also be able to sponsor drinks/snacks if we need 🍿  🍸

**Comment by gausby** [comment]
I think I have a venue for February 22. Awaiting a confirmation on this and then I will announce the venue and create the meet up on meetup.com

@casperstorm let's have a meet up at Rainmaking Loft in the future :)

**Comment by gausby** [comment]
Thanks to Falcon IO for hosting the meet up.

I think that it was a fantastic meet up; please provide feedback so we can avoid making mistakes in the future :)
