### ISSUE TITLE
Copenhagen Elixir and Erlang Meet Up, March 2017

### ISSUE THREAD

**Issue by gausby** [cphex/cphex#51]
**Date and time**: Tuesday, March 28, time: 17h30–20h00
**Venue**:

> Founders A/S
> Skelbækgade 2, 5.
> 1717 Copenhagen

---

We need to find and decide upon:

- [x] What type of event: workshop
- [x] a venue
- [x] a date (March 28)
- [x] food/drink/snacks ?

**Comment by gausby** [comment]
We will do a workshop in collaboration with Foo Cafe.

Any good ideas for a workshop; what do you wanna work with? (Phoenix, Elixir, etc?)

**Comment by mlusiak** [comment]
I'm currently diving into Elixir world. Would be happy to have some crash course on Phoenix.

**Comment by gausby** [comment]
@mlusiak cool. I've been thinking about a simple twitter-clone build with phoenix that we could do; we will not care about persisting the messages, only setting up the processes storing the timelines and a web-interface for showing them.

Don't know if that is too big of a task.

**Comment by gausby** [comment]
On a second thought, that might be a bit ambitious; But perhaps a (non-persisted) micro-blog in phoenix would be easy enough—the posts are stored in a list which lives in a process.

**Comment by Hanspagh** [comment]
Sounds interesting, I have been wanting to try out some of changes they did in 1.3.0 RC.

**Comment by gausby** [comment]
@Hanspagh I haven't played with Phoenix in a long while as well; let's try to make a microblog :)—I was in talks with foo cafe about creating the event in collaboration with them, but I don't know if I have been too late with my organising: If all else fails, could we have the event at Spilhuset ?

**Comment by gausby** [comment]
I am figuring something out with the venue. Radiate (former Foo Cafe) will help out with the venue.

Also, I've moved the meeting to tuesday and announced it on meetup.com

**Comment by Hanspagh** [comment]
Sorry for late response, seems like you found a venue. But you always welcome at spilhuset :)

**Comment by gausby** [comment]
@Hanspagh let's visit spilhuset in April then :)

**Comment by mlusiak** [comment]
Unfortunately I'll have to pass if it's on Tuesday, but I'll follow future events.

**Comment by Hanspagh** [comment]
Seems like a some new people are joining. Should we prepare some sort of elixir/phoenix  presentation or should we just point people to http://www.phoenixframework.org.

**Comment by gausby** [comment]
@Hanspagh I guess it is too late for me to prepare a presentation…it would be amazing if you have one up your sleeve, but otherwise I just say we will split into groups and work in pairs.

**Comment by Hanspagh** [comment]
I am confused, are the event today or next tuesday.
Here its says the 28 and its the same on meetup, but the twitter account seem to disagree

**Comment by gausby** [comment]
It was me brain farting. Sorry about that.

I consider stepping back for a while—I'll help out with the organisation, and such, but I kinda wanna take a break for a while and see where someone else can take it.

The meet up is next week. Sorry about the confusion.

**Comment by Hanspagh** [comment]
Awesome 👍 
I will try to prepare some sort of presentation, and see how it goes. 
Sad to hear to your are considering stepping back

**Comment by Hanspagh** [comment]
I made this, any feedback would be appreciated
https://docs.google.com/presentation/d/1nVoS3nVCXCNv6Mqs04e9yveiLbXj5ceNgrkshXj1ueA/edit?usp=sharing

**Comment by gausby** [comment]
Thank you @Hanspagh for your presentation—I am going to close this issue :)
