### ISSUE TITLE
Copenhagen Elixir and Erlang Meet Up, April 2017

### ISSUE THREAD

**Issue by niklasnisbeth** [cphex/cphex#52]
**Date and time:** Tuesday, April 25, time: 17h30–20h00
**Venue**: TBD

Did we find a venue?

Does anybody want to give a presentation? Hans' introduction to Phoenix last time went over very well, I think, and also seemed like a nice starting point for all the following conversation. Maybe a more general OTP talk could also work? I know that's something I'd like to hear.

**Comment by gausby** [comment]
Anything in particular about OTP we wanna hear about? Supervision and such?

Also, I can ask if we can have the meeting at ShopGun if no one else can host.

**Comment by niklasnisbeth** [comment]
I think it's more important what people want to talk about!

@Hanspagh mentioned Spilhuset as a possible venue last round - maybe that's still on? Else Shopgun is always good.

**Comment by gausby** [comment]
I'll try to contact Hans about Spilhuset.

I asked more of personal interest; OTP are a huge topic (group of topics) and I think I can give a basic introduction to many of the topics.

**Comment by Hanspagh** [comment]
You are very welcome at spilhuset 😊

**Comment by gausby** [comment]
Okay, should I announce an event for April 25, 17h30–20h00 on meetup.com ? cc: @Hanspagh, @niklasnisbeth

**Comment by niklasnisbeth** [comment]
I think you should!

An introduction to supervision would be great if you have time to
prepare.

**Comment by gausby** [comment]
There, [I've scheduled the meet up on the meet up page](https://www.meetup.com/CPHEX-Copenhagen-Elixir/events/239249165/).

I think I can prepare a thing or two about supervision.

**Comment by Hanspagh** [comment]
The address is
 Pilestraede 43, 1st Floor
1112 Copenhagen
Denmark
I will be there all day
