### ISSUE TITLE
Copenhagen Elixir and Erlang Meet Up, May 2017

### ISSUE THREAD

**Issue by skovsgaard** [cphex/cphex#53]
**Date and time:** 30th of May 2017, 1700h
**Venue:** TBD

Initial question I guess is when's a good time?

**Comment by gausby** [comment]
Monday or Tuesday next week?

**Comment by skovsgaard** [comment]
Should we just settle on the 23rd then?

**Comment by gausby** [comment]
Let's!…or we could go with monday or tuesday the week after—would give us more time to tweet about the meet up?

Anyone who has anything they wanna talk about?

**Comment by niklasnisbeth** [comment]
I'm booked next week, unfortunately, but I liked our supervision talk
last time.

**Comment by skovsgaard** [comment]
@gausby, I'm setting this for the 30th for now to give ample time to tweet about it.

**Comment by gausby** [comment]
@skovsgaard I'll ask at the office tomorrow if anyone wanna give a talk…we might have something to share, and then I'll announce on meetup-com, and start tweeting about it.

**Comment by gausby** [comment]
We can talk a bit about our (ShopGun) Erlang GraphQL implementation and answer questions Tuesday next week. Are we okay with that plan?

**Comment by skovsgaard** [comment]
That sounds great. Is ShopGun up for hosting us too?

**Comment by oscarftoro** [comment]
That sounds super interesting!, just consider that the same day there is a Clojure/F# coding dojo
https://www.meetup.com/Copenhagen-Clojure-Meetup/events/238795562/

**Comment by gausby** [comment]
I'll ask if we can host tomorrow; I am pretty sure we can. I'll announce on meetup tomorrow.

**Comment by gausby** [comment]
The meeting has been announced: https://twitter.com/cph_ex/status/867465877935017984

Please share with your friends and family :)
