### ISSUE TITLE
Copenhagen Elixir and Erlang Meet Up, June 2017

### ISSUE THREAD

**Issue by gausby** [cphex/cphex#54]
Let's do a meet up next week. We need to find a date—we need to figure out what day Funktionelle Københavnere has their meet up so we don't overlap.

I think that we should just do some casual hacking. Most people are probably at festivals or elsewhere.

We can most likely use the ShopGun offices, but if anyone else has a venue we will pick that one so we get to be different places.

**Comment by niklasnisbeth** [comment]
I'm on holiday. Catch you next time.

**Comment by skovsgaard** [comment]
F#unktionelle Københavnere has their next meetup on the 27th (this Tuesday), so any date that isn't that should work. How's Wednesday?

**Comment by gausby** [comment]
Let's go for Wednesday!

**Comment by gausby** [comment]
I've announced the meet up on the horrible meetup-dot-com https://www.meetup.com/CPHEX-Copenhagen-Elixir/events/241029174/

**Comment by skovsgaard** [comment]
Cool. Is ShopGun cool to host; I'm not sure we can find any other place on this short a notice?

**Comment by gausby** [comment]
I am 99% sure we are; just need to clear it on Monday

**Comment by skovsgaard** [comment]
Perfect. I guess we're not in any more of a rush than that.

**Comment by gausby** [comment]
We can have the meeting at the ShopGun offices; I've updated the meetup invitation.
