### ISSUE TITLE
Copenhagen Elixir and Erlang Meet Up, July 2017

### ISSUE THREAD

**Issue by gausby** [cphex/cphex#55]
**Date and time**: Wednesday, July 26, time: TBD
**Venue**:

> TBD

---

We need to find and decide upon:

- [x] What type of event: talks and presentations
- [ ] a venue
- [x] a date (July 26)
- [ ] food/drink/snacks ?

**Comment by gausby** [comment]
I am going to give a presentation on building a MQTT client in Elixir at ElixirConf US in September, so I offer to prepare the presentation at give a first rough cut at this meet up.

Anyone else up for giving a presentation?

**Comment by niklasnisbeth** [comment]
How about doing something in september? I can maybe arrange for a room at Founder's House.

**Comment by gausby** [comment]
I'll be home from Canada around September 20—so I would vote for the end of the month. Please open an issue if you like. I'll help out as much as I can from here :)
