### ISSUE TITLE
Copenhagen Elixir & Erlang meet-up, September 26 2017

### ISSUE THREAD

**Issue by niklasnisbeth** [cphex/cphex#56]
We will be meeting at Founder's House, Njalsgade 21G, 7th floor, on the 26th from 6 o'clock.

Anybody up for presenting something?

- [x] Date
- [x] Venue
- [ ] Stuff to talk about

**Comment by niklasnisbeth** [comment]
OK, we have use of the kitchen/canteen at Founder's House. Njalsgade 21G, 7th floor. From 18.00.

Anybody coming? :)

**Comment by gausby** [comment]
Sorry for being a bit late announcing the meet up. I've been traveling, and also I am jet lagged. The meet up page is here: https://www.meetup.com/CPHEX-Copenhagen-Elixir/events/243572177/

**Comment by casperin** [comment]
I actually really would like to go, but it's exactly at the same time as [this one](https://www.meetup.com/MoedegruppeFunktionelleKoebenhavnere/events/242976531/) :-(

**Comment by niklasnisbeth** [comment]
Hasn't this come up before? Maybe we should switch to wednesdays in the
future.

**Comment by casperin** [comment]
Not my call of course, but Wednesdays would be perfect for me :)

**Comment by gausby** [comment]
Wednesdays are fine by me. There are no days that fit everyone, so I'd just say it's up to the organiser of the meet up to pick a date that works for them :)

**Comment by niklasnisbeth** [comment]
Let's stick with the 26th for this one but try not overlap with FK next
time.. I don't do meetup.com so I wasn't aware :/

**Comment by casperin** [comment]
Np. I'll see you next time then :)
