### ISSUE TITLE
CPHEX October meet-up - GenStage?

### ISSUE THREAD

**Issue by niklasnisbeth** [cphex/cphex#57]
At the last meet-up, we talked about having an event focused on GenStage[0]. We probably won't find an expert to do a presentation, so we can try to learn together! Maybe we could do a little pair-programming exercise based on one of the many talks or blog posts.

To avoid conflicts with the F#ers, let's have the meet-up on a wednesday - I suggest October 18th. If it clashes with some obviously related meet-up or event, or we can't find a venue for that date, we can move it to the 25th. Let's decide in a few days so we can start to drum up interest.

Anyone up for hosting?

[0] https://elixir-lang.org/blog/2016/07/14/announcing-genstage/

**Comment by skovsgaard** [comment]
I'm game. I don't have a venue though.

**Comment by gausby** [comment]
As always we could do it at shopgun, but it is nice go to other venues once in a while :)

**Comment by niklasnisbeth** [comment]
Let's do it at Shopgun if there are no other takers. 18.00?

**Comment by gausby** [comment]
Shopgun, October 18 at 18h00 it will be then!

Do you have suggestions to what kinda data we should work with?

**Comment by niklasnisbeth** [comment]
Cool!

https://wikitech.wikimedia.org/wiki/EventStreams was suggested on
Twitter. I don't know if it gets too complicated?

**Comment by gausby** [comment]
I think GitHub has some kind of public event stream. Perhaps we could do something with that.

**Comment by gausby** [comment]
Sorry, I was a bit late with announcing the meetup on the dreaded meet-up-dot-com. Perhaps I should share the social media accounts with some of you so we can do some more/better advertisement.

**Comment by niklasnisbeth** [comment]
Yeah, we can talk about it wednesday - see you!
