### ISSUE TITLE
CphEx February 2018 Meet Up

### ISSUE THREAD

**Issue by gausby** [cphex/cphex#58]
This meet up will take place February 28, at 18h00 to 20h00 at ShopGun:

**Venue**: 
> **ShopGun**
> Arne Jacobsens Allé 16, 3.
> 2300 Copenhagen S
> [Map](https://goo.gl/maps/GXS0K)

Sign up here: https://www.meetup.com/CPHEX-Copenhagen-Elixir/events/248069630/

* * *

- [x] Date
- [X] Venue
- [x] Stuff to talk about

**Comment by gausby** [comment]
I kinda dropped the ball on making events the last couple of months, let's get the ball rolling again.

Anyone who has suggestions to how we can attract more people? It would be great to see some new faces, have more people speaking, etc.

**Comment by niklasnisbeth** [comment]
I can only say that I agree. I'm unlikely to be able to attend this
month but I hope we can get things going again.

**Comment by trarbr** [comment]
Hi there 😄  I'm a new face here, but I'd like to come and give a talk, and I can probably bring a couple of colleagues. We've been bringing Elixir into production on a couple of projects, and I would like to come share some of what we've learned. I'm considering a couple different topics:

1. Code organization / "patterns". When to add a new function, when to add a new module. What makes code readable and maintainable? And testable? 
2. Deployment and monitoring (our process is based on Distillery, Conform, Ansible and Prometheus, deployed on native or VM). How to do configuration that works both in dev and prod. Tips and tricks for logging and metrics. 
3. Utilizing distribution to increase service availability, both in failure-cases and for non-hot upgrades (what do you call those? Cold upgrades?). How it changes deployment, multiple releases from the same umbrella, cross-node communication, service discovery, etc.

No matter the topic, it would be based on what works for us (as newbies in the BEAM community), and utilize practical examples. As I haven't been to any of your priors events, I don't know what duration works best, or how experienced the audience is. I think the topics are beginner-to-intermediate, and I'd probably prefer a 30 minute talk with discussions afterwards, but I don't know how that works?

I will also be talking at ElixirConfEU, so this is kind of a practice session (though not entirely the same talk).

Date-wise, I'm hoping to late February to mid March. I'm from Svendborg so it would be nice to know in advance (especially if you'd like me to give a talk :wink: ).

**Comment by Hanspagh** [comment]
Awesome, I am really looking forward to these events again. I could also do sort of a presentation of one of the projects I have been working on in elixir.

**Comment by gausby** [comment]
It would be great with presentations featuring projects running in the wild—so far most of the presentations I've personally given has been abstract (on let it crash philosophy, about supervision, why and where Elixir/Erlang fit in, etc.)—more tangible use cases could be interesting.

@Hanspagh awesome; would you prefer the latter part of February, or mid march? I think an event with you and @trarbr presenting could be interesting.

@trarbr I think all the topics are interesting, but I think the topic of how-to-deploy-the-baby is the most interesting. We use relx and rebar, so personally I would like to hear about distillery—and I sense one of the concerns in the community is about how to deploy and run Elixir in production.

This looks like this one is going to be a great meet up :)

**Comment by Hanspagh** [comment]
Actually we are also using distillery and conform, so it might make sense to do it on the same evening. A part from that I could talk about how we used gen-servers and phoenix channels to build our product.

**Comment by trarbr** [comment]
That sounds great. I can talk about how we deploy, tradeoffs we made, etc. We're not currently using distribution or hot-code upgrades, but we're looking into it for one of our systems, so maybe I'll have time to include some of that as well.

I'm open for suggestions on dates, but I'm in Copenhagen anyway on March 14th (and probably either 13th or 15th as well), so that would suit me well.

**Comment by gausby** [comment]
Let's start planning the march meet up then :)

I'd say we still do a small meet up in February; no presentations, just casual hacking.

**Comment by ghost** [comment]
Hi Martin!

Are we still planning for a small Meetup this month ? Maybe you could show me your emacs setup ?  Never really got hooked on it, but maybe i should give it a last chance ;-?

**Comment by gausby** [comment]
@telsgaard I got a lot on my plate in February, so I will wait a bit to answer you on that question. I consider doing a get-together in week 9; but I think I will wait till Wednesday to come with a final answer.

**Comment by gausby** [comment]
How about having an informal meet up Monday next week?

Tuesday is the day of Funktionelle Københavnere.

**Comment by ghost** [comment]
Fine for me ;-)

**Comment by gausby** [comment]
actually, how about Wednesday? It would work better for me with having the meetup wednesday, and that would give a couple of extra days for "marketing".

**Comment by ghost** [comment]
Also fine ;-)

**Comment by gausby** [comment]
We can most likely be at ShopGun, but as always, it would be nice to see other venues too; so if I cannot find another venue it will be good old ShopGun :)

**Comment by gausby** [comment]
The meet up has been announced here: https://www.meetup.com/CPHEX-Copenhagen-Elixir/events/248069630/

**Comment by gausby** [comment]
I didn't manage to find another venue—I've been a bit busy; so ShopGun it is :)
