### ISSUE TITLE
CphEx March 2018 Meet Up

### ISSUE THREAD

**Issue by gausby** [cphex/cphex#59]
**Date and time:** March 13, 19h00 (this meet up will end around 21h00, we might be able to hang around later if people want)
**Location:**

> **ShopGun**
> Arne Jacobsens Allé 16, 3.
> 2300 Copenhagen S

* * *

Agenda (wip):

- «insert talk title» — @trarbr 

* * *

March 13 we will have a group of people from Svendborg visiting Copenhagen. Troels have volunteered to give a talk, and perhaps Hans might be able to talk as well. I am pretty sure we can host the meet up at ShopGun, but I will leave the venue open just for now.

This discussion spawned from issue #58 

* * *

- [x] Date—it will be March 13, because @trarbr is in town on that day
- [x] Venue
- [x] Food, snacks
- [x] Stuff to talk about

**Comment by gausby** [comment]
@Hanspagh & @trarbr you both were willing to give a talk, right ?

Should I announce the meet up on march 14 ?

**Comment by trarbr** [comment]
Yes, I'm still up for it. March 13th will actually be best for me, as I'm in Copenhagen on the 13th and 14th.

**Comment by gausby** [comment]
Then March 13 it will be!

**Comment by Hanspagh** [comment]
I have a lot of work atm, but I will see if I can prepare something

**Comment by gausby** [comment]
I am sure ShopGun will host this meet up, but let's see if somewhere else will be up for it…I will try to do a bit more marketing than I've done recently. Hopefully we will be able to gather a bigger attendance that way.

**Comment by gausby** [comment]
I will announce the meetup on meetup.com and do some promotion.

I don't have a venue yet, but as said, I am pretty sure ShopGun will host.

**Comment by gausby** [comment]
I've announced the meet up here: https://www.meetup.com/CPHEX-Copenhagen-Elixir/events/248466542/

I set ShopGun as the venue.

**Comment by gausby** [comment]
And I decided on 19h00-21h00—this is a test; I want to see if placing the meet up later in the evening will give better turnouts.

**Comment by gausby** [comment]
@trarbr do you have a title for your talk ?

**Comment by trarbr** [comment]
Hmm.. "Elixir deployments with Distillery and Ansible" ? And then maybe some associated tricks

**Comment by Hanspagh** [comment]
I wont be able to do a talk, but I am gonna be there tomorrow

**Comment by gausby** [comment]
That is okay; looking forward to seeing you :)

**Comment by gausby** [comment]
Closing this one. It was a great meet up!
