### ISSUE TITLE
I've stepped down as an organiser on the meetup.com group

### ISSUE THREAD

**Issue by gausby** [cphex/cphex#60]
I am sorry to say that I've stepped down as an organiser on meetup.com.

I haven't had the time to organise meetups the last couple of months, and I hope someone else can pick up the baton—someone who can hopefully be more successful in creating excitement about Elixir.

If anyone want me to come and give a talk about Elixir I will most likely say «yes» :)…but I will focus my efforts elsewhere than organising every month—I hope someone else will do that.

**Comment by ghost** [comment]
Sorry to hear Martin, you did a good job! For those interested in Erlang, i will try to continue in a group dedicated to Erlang: https://www.meetup.com/Erlang-Copenhagen/ you can come and talk with excitement about Erlang ;-)
