### ISSUE TITLE
Elixir meetup November 

### ISSUE THREAD

**Issue by Hanspagh** [cphex/cphex#61]
We wanted to get the ball rolling again and start planing a monthly meetup. This will be the first one, I have prepared a small introduction to gen_statem, but it would be awesome if somebody else would a presentation aswell

**Date and time:** November 20, 18h00 
**Location**:

> Mearsk
> Esplanaden 50, 
> 1098 København K
> If you get lost ask for Me (Hans Pagh) in the reception or call me directly on 30668964

**Agenda** (wip):

- Introduction
- Introduction to gen_statem /  gen_state_machine @Hanspagh 
- Building an efficient micro-service in Elixir @haljin

**Comment by niklasnisbeth** [comment]
Great to see some activity here! I am unable to attend but I hope to join in the future.

**Comment by Hanspagh** [comment]
To make access to Maersk as smooth as possible, it would be nice to have an idea of how many people are coming. Would people mind to comment on this ticket if they intend to come

**Comment by thehabbos007** [comment]
I intend to come :)

**Comment by DenLilleMand** [comment]
I am coming as well

**Comment by haljin** [comment]
I'm going to bring 9 people myself included :)

**Comment by haljin** [comment]
@Leonidas-from-XIV

**Comment by Leonidas-from-XIV** [comment]
Yes, I think I will join.

**Comment by Hanspagh** [comment]
Slides and code from my talk is here https://github.com/Hanspagh/intro_gen_state_machine
