### ISSUE TITLE
Elixir meetup January

### ISSUE THREAD

**Issue by Hanspagh** [cphex/cphex#62]
We had a great meetup last time, but decided will skip the meetup in December, because it is December. Next meetup will be in January, and Motorola will be happy to host, the topic might be something more hands-on coding. Learnings from last time were that its hard to know who is coming or not, so as soon as we have a date, I will make a doodle to see if that will work better.

Date and time: Jan 21 18:00
Food: Sponsered by Motorola Solutions Danmark
Topic: Nerves
Location:

    Motorola Solutions Danmark
    Sydvestvej 15, 2600 Glostrup

Agenda (WIP):
* Introduction
* Time dependent sensor readings with NIFs by Ahmad Sattar
* Food 
* OTP and K8s: friends or foes? by Maarten

Do you intend to come please sign up here:
https://doodle.com/poll/pk28pmasbz7p4zye

**Comment by haljin** [comment]
Here's the location:

https://www.google.com/maps/place/Motorola+Solutions+Danmark+A%2FS/@55.6631816,12.3932873,17z/data=!3m1!4b1!4m5!3m4!1s0x4652572d81ae2f9b:0x3ccbcaf5a6ca9369!8m2!3d55.6631816!4d12.3954814

Keep in mind that in the afternoon (I assume we are aiming at 18 :)) the main door from Sydvestvej is closed, so you have to go round back and call "Motorola 2. sal" to be let in. You can also shoot me a PM on Elixir Slack. 

There will be food ordered, so please do sign up so we know how many are coming.

**Comment by rootkc** [comment]
When will you know what will be on the agenda?

**Comment by Hanspagh** [comment]
I just updated the agenda

**Comment by thehabbos007** [comment]
Link to slides and code of NIF presentation: https://github.com/thehabbos007/nerves-hc-sr04-distance

**Comment by Hanspagh** [comment]
Thanks for a good meetup
