### ISSUE TITLE
Elixir Meetup June '23

### ISSUE THREAD

**Issue by guillego** [cphex/cphex#64]
### Meetup on June 22nd, 2023
_Note: React with a thumbs up 👍 **only** if you are planning to attend! Feel free to use any other emojis to express excitement!_
[Meetup link](https://www.meetup.com/copenhagen-elixir-meetup-group/events/294283649/)

Date and time: 22/06 - 17:30
Topics:
- Some awesome things you can do with LiveView - 15/20 min (@madsobel)
    - [Live cursor demo](https://github.com/madsobel/livecursor)
    - [CS GO demo](https://github.com/madsobel/csgo)
- Using Elixir and Liveview to monitor Kubernetes - 15/20 min (@Hanspagh)

Location: [Maersk offices at Oslo Plads 2](https://goo.gl/maps/CRhjHQLXT7okQWEk6) (next to Østerport station)
You can use the back entrance as shown on the map (Write to @Hanspagh on slack or on 30668964 and he will open for you)
![image](https://github.com/cphex/cphex/assets/1024416/c1379b48-9044-45b1-9a1a-b24c51791e96)

Agenda:

1. Introduction
2. LiveView presentation
3. Elixir at Maersk
5. Food+drinks
6. Discussions

**Comment by guillego** [comment]
@Hanspagh can you help me out with fleshing out the details of the event?

**Comment by Hanspagh** [comment]
If Mearsk is hosting then I am available on the 19 or 22 of June. I was not at the previous meetup and would be curious to know how much experience with Elixir people have. Previously finding the right detail level for a presentation has been one of the challenges, so it would great to know.

**Comment by guillego** [comment]
Shall we do the 22nd? It's a Thursday like the last time we met in may!

From the May meetup it seemed like I was the least experienced with Elixir (still familiar with the primitives of the language and the BEAM). If I recall correctly, 3/6 people work with Elixir/Phoenix in production and 2 have a few years of experience dabbling with it in some fashion either at work or on personal projects @Hanspagh

**Comment by killerkiara** [comment]
Hello everyone!
I am fairly new to Elixir, started working with it in March this year.
I am very happy to discover there are some Elixir meetups in Copenhagen. I have been previously programming Ruby for +10 years and active in the Ruby community in Berlin (and a bit in Copenhagen too). I'll be happy to help with the organisation if needed.

**Comment by guillego** [comment]
Hey @killerkiara thanks so much for offering to help! We have just started re-organizing recently in the [Elixir Slack workspace](https://join.slack.com/t/elixir-lang/shared_invite/zt-1uzc7ctaf-N97LcwUbMxScYFLnw7Kf0g), so cool to have more people joining!

**Comment by Hanspagh** [comment]
Let's set the date to 22/6 I will be back with more information about the location etc. Do we have a good way to get sort of a head count?

**Comment by guillego** [comment]
Whoever is interested in attending, please react with a thumbs up to the issue description! 👍

**Comment by ErikMejerHansen** [comment]
Super exciting 🎉. I'm part of the first team at Maersk with Elixir as our tech stack. I'll see if I can't drag the rest of my team with me :)

**Comment by guillego** [comment]
We're approaching the meetup date! It's really cool to see how the attendance has gone up (10 people 👍 so far)

We still have some things to sort out:
- @Hanspagh do you have any updates on exact location/time?
- @madsobel can you confirm the talk topic and length?
- @Hanspagh can you confirm the talk topic and length?

I've never given a tech talk (outside of work) so if those two are confirm I'd rather wait for the next meetup with my talk, but otherwise happy to just do it and see what happens 😅

**Comment by Hanspagh** [comment]
Location & Time: 
I would propose 17:30, if that works for the rest. Depending on attendance from Mearsk, we will be either at our main office at Esplanaden 50 (Which requires everybody to get nametags and go through security) or at our shared office space at Oslo Plads at Østerport st (Which is a bit easier). We will order some pizza and beers + soda, so it is quite important that everybody that wanna join 👍 the main post.

Talk: 
Sure, I can present our solution, I will mostly go through how we have used various elixir libs/tools to solve our problem, and maybe show some code, depending on how many how code/how many questions there are, I would think around 15/20 min.

**Comment by guillego** [comment]
Sounds amazing @Hanspagh! Let us know when you have a location confirmed 😄

**Comment by madsobel** [comment]
@guillego I think the title is fine, although it should probably be “_some_ of the awesome things you can do with LiveView” 😅. I will try to demo a few examples of real-time updates combined with PubSub. 
I think the length should also be around 15-20 minutes 🙌

**Comment by guillego** [comment]
Super cool! Thanks @madsobel looks like we have a full program!

**Comment by lehoff** [comment]
Apart from giving a 👍 to the issue is there anything else I have to do to be signed up?

**Comment by guillego** [comment]
@lehoff that should be it! Just stay tuned for the last details on location as soon as we have them!

**Comment by guillego** [comment]
@ErikMejerHansen has created a meetup group so that it's easier to share and sign up, and more people can find the meetup!
https://www.meetup.com/copenhagen-elixir-meetup-group/

**Comment by vanjacosic** [comment]
Hey all 👋 

I'm a co-organizer of the Rust meetup and I have been wanting an Elixir meetup to go to for a long time, so I created a group on Meetup.com back in January: https://www.meetup.com/copenhagen-elixir-community/

I only found this thread yesterday because Hans sent me a message about it. I wasn't following the repo because I thought it was dead 🙈 My plan was to do the first event some time in July, but I see you are already at for this month, so will definitely see you there on Thursday!

I've been trying to reach out to former organizers and attendees to get it going, but it's taken some time to get replies and find people willing to help out. In the meantime I created some graphics and worked on a basic static website. I also set up a place for organizers to chat on a shared Discord server with other meetups.

I was going to mention it when I saw you all there, but I see now that @ErikMejerHansen made a new group as well. It seems like it would make sense to join the efforts? What do y'all think? 

(BTW. we also have an endless conversation going in the Rust group about Meetup.com being awful and what alternatives we can use, but for now it's the best option for getting the word out.)

**Comment by guillego** [comment]
Hey @vanjacosic, this is really exciting! I think we definitely should join efforts so let's have a discussion about it on Thursday to see how we want the community to move forward.
We had some of the initial discussions in the #denmark channel of the [Elixir Slack Workspace](https://join.slack.com/t/elixir-lang/shared_invite/zt-1xky37xsj-9eAmbQHJ_kspA4bKBLbouQ).

**Comment by guillego** [comment]
Thanks everyone for a fantastic meetup!! Updated the description with the repos from @madsobel's demos.

As we discussed, let's open new threads to discuss the next meetup, communication channels, etc!

I'll close this thread in a few days.

**Comment by ErikMejerHansen** [comment]
Thank you so much for getting the Meetups up and running again. Looking forward to the next one 🎉
