### ISSUE TITLE
Elixir Meetup July '23

### ISSUE THREAD

**Issue by guillego** [cphex/cphex#66]
July 2023 meetup

[Sign up via Meetup!](https://www.meetup.com/copenhagen-elixir-meetup-group/events/294756762)

Date and time: 20th of July - 17:30
Topic(s): 
- `:cowboy` REST handlers to build APIs (@ErikMejerHansen)
- TBD

Location: [Copenhagen FinTech Lab](https://goo.gl/maps/vXU1BDvtMthLU4Vk7)

Agenda:
1. Intro
2. Talk 1
3. TBD

**Comment by guillego** [comment]
In the last meetup we agreed that we can continue with the "trend" of having the meetups on the third Thursday of every month, that is July 20th for the next one.

Unfortunately I'll be out of Copenhagen then, so if anyone who is available can step in and coordinate for this one it would be great!

**Comment by killerkiara** [comment]
Hello guys, as @guillego has asked me, I can help coordinate the next meetup. 
How does July 20th sound as a date? 

If you are available, please react with 👍🏽 in the issue description.

**Comment by Hanspagh** [comment]
I am out most of July, so I will have to skip this one.

**Comment by ErikMejerHansen** [comment]
I can give a presentation on using `:cowboy` REST handlers to build APIs.

**Comment by vanjacosic** [comment]
20th works for me!
In the Rust group we've been experimenting with recording talks for those that can't make it. So I will try to bring the audio and video gear as well 😊 Though, only if the speakers want their talks to be recorded.

**Comment by killerkiara** [comment]
Hello everyone, any updates here? @guillego had asked me to update the description while we have more info, but I am not able to edit it, seems. Could we confirm the 20th as a date, to begin with?

**Comment by Munksgaard** [comment]
20th works for me as well :-)

**Comment by ErikMejerHansen** [comment]
20th is good for me. 
Anyone willing to host?  I'm on vacation until a couple of days before the meetup so I'm unsure if I can find us place at Maersk.

**Comment by Munksgaard** [comment]
Depending on how many we are, I can host us at [Copenhagen FinTech Lab](https://goo.gl/maps/vXU1BDvtMthLU4Vk7). We can use the lounge, which will seat around 20 people (if necessary, we might be able to pull in some extra chairs and tables from somewhere).

**Comment by guillego** [comment]
Hey there! We are trying to contact @skovsgaard to get more access to the organization/repo so that people can edit threads (right now only @Hanspagh is able to).

I updated the description with the latest details! Feel free to ping me on slack if there's anything that needs to be updated.

**Comment by guillego** [comment]
Also @ErikMejerHansen do you want to make a meetup event for this?

**Comment by ErikMejerHansen** [comment]
@guillego Meetup created. I set the starting time to 17:30 like last time: https://www.meetup.com/copenhagen-elixir-meetup-group/events/294756762 

@Munksgaard Thanks for hosting 🎉 Do you need names of attendees in advance? Or any help setting up?

**Comment by Munksgaard** [comment]
> @guillego Meetup created. I set the starting time to 17:30 like last time: https://www.meetup.com/copenhagen-elixir-meetup-group/events/294756762

It seems like the event is not currently "open", at least I cannot find any way to attend it as it is.

> @Munksgaard Thanks for hosting tada Do you need names of attendees in advance? Or any help setting up?

I don't think I need names, but a rough estimate of the number of attendees would be nice. And yeah, perhaps some help with the setup. We might need to find some extra chairs and tables.

What did you guys do for food last time?

**Comment by killerkiara** [comment]
@ErikMejerHansen I also see the meetup event as "not open" (cannot attend).

@Munksgaard If you guys need help with the organization or for example food ordering I am available.

**Comment by ErikMejerHansen** [comment]
Thanks for the heads-up. Event should now show as open.

**Comment by sepow** [comment]
> I don't think I need names, but a rough estimate of the number of attendees would be nice. And yeah, perhaps some help with the setup. We might need to find some extra chairs and tables.

I can come by early and help out if needed.

**Comment by killerkiara** [comment]
Hello people!
Looking forward to meeting you later! Any specific info we need to be able to enter the building, @Munksgaard?

**Comment by Munksgaard** [comment]
Edit:

Use the doorphone and choose LEAF -> Philip Munksgaard to call me, then I can let you in. There's a lot of construction going at the moment, so the door is obscured by a large lift.

The lounge, where we'll be, is on the second floor, to the left.

I'll try to be down by the door at around 17:30 to let the first people in. If anyone wants to come early and help out, I'll start getting ready from 17:00 (though I don't think there's going to be much to do).
