### ISSUE TITLE
Elixir Meetup September '23

### ISSUE THREAD

**Issue by ErikMejerHansen** [cphex/cphex#68]
# September 2023 meetup

[Sign up via Meetup!](https://www.meetup.com/copenhagen-elixir-meetup-group/events/295607145/) 

## Date and time
 21st of September 2023 - 17:30

## Topic(s)
- @guillego Nerves
- @ErikMejerHansen Stuff I learned while building a collaborative editing app

## Location:
- We'll be at Triforks office: Gdanskgade 2, 2150 København
[Google Maps](https://goo.gl/maps/MnhWwe9fnPg8W3VA6)

## Agenda:
- To be determined

**Comment by ErikMejerHansen** [comment]
I'd love to hear about Nerves or Broadway if anyone is open to saying a few words about those.

**Comment by simonelnahas** [comment]
Hey! We can be at Triforks new office in Nordhavn Gdanskgade 2. I booked a room for 18 people, let me know if we need a bigger one.

**Comment by ErikMejerHansen** [comment]
That sounds great @simonelnahas! Thanks for hosting. We haven't been more than 18 people yet. I'll keep you updated on the RSVPs.

**Comment by ErikMejerHansen** [comment]
I might be able to say something about building a collaborative editing app with Phoenix: Channels and PubSub mostly, but it would be on a very introductory.

**Comment by thehabbos007** [comment]
I don't think i can attend this time due to overlapping school work. Will try to clear up for next time, though!

**Comment by guillego** [comment]
Hello! Thanks for keeping this up and running @ErikMejerHansen
I'd be super happy to give a short talk about Nerves and my journey from 0 experience with Elixir in production to deploying a Nerves-based hardware prototype!

It could either be more of a "story" based presentation of my experience, pitfalls, learnings, etc. Or it could also be a more hands-on approach where I start with a blank raspberry pi and live-build something with it.

**Comment by Munksgaard** [comment]
> It could either be more of a "story" based presentation of my experience, pitfalls, learnings, etc. Or it could also be a more hands-on approach where I start with a blank raspberry pi and live-build something with it.

Both sound great, and now I'm really sorry that I won't be able to attend :D

**Comment by guillego** [comment]
Hey there! Is there anything that needs to be organized ahead of time? Food, refreshments?

**Comment by ErikMejerHansen** [comment]
Hi @guillego, the last few times we've started by sending out a shared order for pizza and then gotten the first talk going while the pizzas were en route. 
That seemed to have worked well enough, but definitely open to handling this differently. 
I will say that I think it's important that there isn't an implied expectation that the folks who are kind enough to host also have to provide drinks and snacks. 

Edit: Previously stated "but _defiantly_ open" - which was the opposite of what I was aiming at 😳

**Comment by ErikMejerHansen** [comment]
I've dropped my slides for "Robots and Collaborative Coding" in both keynote and PDF format here: https://github.com/ErikMejerHansen/cphex_presentations/tree/main/presentations/robots_and_collaborative_editing

Thanks for fun meetup!
