### ISSUE TITLE
Elixir Meetup November '23

### ISSUE THREAD

**Issue by ErikMejerHansen** [cphex/cphex#70]
# Elixir Meetup November '23
[Sign up via Meetup!](https://meetu.ps/e/MC9s9/y5gqF/i)

Got an idea for a talk or topic? Comment below. We're always looking for talks, topics and presenters :)
Willing to host? Awesome! Comment below (and thank you 🤩)

## Date and time
 16th of November 2023 - 17:30 to ~19:00

## Topic(s)
- Deploying Elixir applications using Nix
- To be determined

## Location:
BLOXHUB - Bryghusgade 8, 1473 København 
[Google Maps](https://maps.app.goo.gl/HW25LyNJKnWkfGxU9)

## Agenda:
To be determined

**Comment by Munksgaard** [comment]
I can talk about deploying Elixir applications using Nix.

**Comment by Munksgaard** [comment]
Oh, and the link in the description leads to this issue instead of the meetup.

**Comment by ErikMejerHansen** [comment]
> Oh, and the link in the description leads to this issue instead of the meetup.

Fixed!

**Comment by ErikMejerHansen** [comment]
Hi @guillego and @vanjacosic,

Something urgent has come up and I'm unable to attend tonights Meetup. Hope you have a good one!
