### ISSUE TITLE
Should we hold December Meetup or skip it

### ISSUE THREAD

**Issue by ErikMejerHansen** [cphex/cphex#71]
Hi Folks,

With our normal schedule of having meetups on the third Thursday of the month the December meetup would land on the 21st of December. This does not seem like the best timing. 

I imagine that folks have busy calendars in December, so should we just skip December and reconvene on the third Tuesday of January '24?

**Comment by Munksgaard** [comment]
Sounds good to me, I won't be able to make it on the 21st :-)

**Comment by vanjacosic** [comment]
I am also unavailable on the 21st. 

I was thinking that we could do an "Advent of Code with Elixir" / hygge meetup, earlier than the usual date. 
No speakers or agenda, just hacking on the challenges together. But everyone's calendars are usually already stuffed for December so I'm not sure it's doable. 

But at least it wouldn't require much organizing work - specially if @Munksgaard or @killerkiara can book their respective meeting rooms. Could even be on the 5th or 7th before December really gets busy 🎅  thoughts?

**Comment by killerkiara** [comment]
I don't think it will be an issue to host again, but I still need to ask for permission :) However, I am not available on December 5th (going to this event, maybe interesting for others among us: https://english.ida.dk/event/privacy-enhancing-technologies-pets-349432). The 7th could work for me, and I will let you know about hosting :)

**Comment by Munksgaard** [comment]
I would love to do some AoC-hacking. I'm not sure that either the 5th or the 7th works for me, but don't let that hinder the rest of you.
