### ISSUE TITLE
Cancelled: Elixir Meetup February '24

### ISSUE THREAD

**Issue by ErikMejerHansen** [cphex/cphex#72]
# Cancelled!

~~# Elixir Meetup February '24~~

~~Got an idea for a talk or topic? Comment below. We're always looking for talks, topics and presenters :)

~~## Date and time~~
~~15th of February 2024 - 17:30 to ~19:00~~
~~Sign up [here](https://www.meetup.com/copenhagen-elixir-meetup/events/298478904/)~~
_Why do I need to sign up?_: It's nice for us to know how many folks we can expect so that we don't begin things too early thinking that everyone is already present. If you don't like meetup then just add a comment to this issue stating that you'll join!~~

~~## Topic(s):~~

~~## Location:~~
~~[Fintech Lab](https://www.google.com/maps/search/?api=1&query=55.67112%2C%2012.585392)~~
~~Applebys Pl. 7, 1411 København K · Copenhagen~~

~~### How to find us:~~
~~Use the door phone and choose LEAF -> Philip Munksgaard to call me, then I can let you in. There's a lot of ~~~~construction going at the moment, so the door is obscured by a large lift.~~

**Comment by ErikMejerHansen** [comment]
There was the suggestion to do a workshop type Meetup centered around  https://adventofcode.com/ in December. Any appetite for doing that this month?

**Comment by ErikMejerHansen** [comment]
And apologies for the short notice on this one, January is going by _fast_.

**Comment by Munksgaard** [comment]
I won't be able to make it this time around, unfortunately, but I look forward to the February meetup!

**Comment by ErikMejerHansen** [comment]
Not a lot of traction on this one (probably may fault with the late announcement and messing up the title the meetup). 
I'll give it a day or so more for a host to show up and suggestions for topics - if that fails I think we'll postpone till February.

**Comment by ErikMejerHansen** [comment]
I think I can have something ready that is a continuation of https://www.youtube.com/watch?v=likfZyXZXj0 about how you might not need a CRDT (conflict-free replicated data type) to do collaborative editing

**Comment by ErikMejerHansen** [comment]
Quick update: I didn't get as far as I had hoped so "You might not need a CRDT" will be _very_ light on Elixir content, but hopefully there will still be a few insights to be gained.
