### ISSUE TITLE
Elixir Meetup March '24

### ISSUE THREAD

**Issue by ErikMejerHansen** [cphex/cphex#73]
# Elixir Meetup March '24

Got an idea for a talk or topic? Comment below. We're always looking for talks, topics and presenters :)

## Date and time

To be determined!

## Topic(s):

- You might not need a CRDT - @ErikMejerHansen 
- Discussion: Queues and schedulers in Elixir
- How do we make the Meetup sustainable?
- [Insert your topic here]

We're always looking for speakers or someone to run a workshop. Please reach out in the thread linked below, if you've got an idea for a topic or talk.

## Date and time
14th of March 2024 - 17:30 to ~19:00

## Signup
Sign up [here](https://www.meetup.com/copenhagen-elixir-meetup/events/299435791/)

Why do I need to sign up? It's nice for us to know how many folks we can expect so that we don't begin things too early thinking that everyone is already present. If you don't like meetup then just add a comment to this issue stating that you'll join!

## Location:

[BLOXHUB](https://www.google.com/maps/search/?api=1&query=55.67224%2C%2012.578703)
Bryghusgade 8 · København

### How to find us:

Enter from Bryghusgade entrance. Ring the door for reception, take the elevator to the 3rd floor, wait at the door to be let in by us or maybe by a receptionist. We will be in meeting room "Copenhagen". If you are going to be early or late, please message Vanja through Meetup.com chat.

**Comment by ErikMejerHansen** [comment]
If we stick to the regular 3rd Thursday of the month schedule this will be on the 21st of March. 
This is my wife's birthday - any objections to running the Meetup on the 14th of March?

**Comment by Munksgaard** [comment]
I'm fine with 14th of March :+1:

**Comment by gausby** [comment]
March 14 is fine with me

**Comment by vanjacosic** [comment]
Works for me too. 

We might be able to be at Blox again if we don't have other options, will know sometime next week 🤞

**Comment by vanjacosic** [comment]
Success, got a room at Bloxhub! I have updated the event and added the relevant details ✅
