### ISSUE TITLE
Elixir Meetup April '24

### ISSUE THREAD

**Issue by ErikMejerHansen** [cphex/cphex#74]
## Elixir Meetup April '24
Got an idea for a talk or topic? Comment below. We're always looking for talks, topics and presenters :)

[Meetup Link](https://www.meetup.com/copenhagen-elixir-meetup/events/300465817/)

## Topic(s):
We're planning on running a introduction to elixir meetup in May. 
Aprils meetup will kickstart the planning for the May meetup. 

## Date and time
24th of April 2024 - 17:30 to ~19:00

## Location:
 Fintech Lab

**Comment by ErikMejerHansen** [comment]
In an _epic_ display of dad-memory I totally forgot that the 24th is my daughters birthday 😱. 
So I can't join on the 24th. I'm still very interested in helping out with the May meetup.

**Comment by gausby** [comment]
Does anyone have a location we can use for this meeting? What do we need—a table to sit around, a projector for a laptop?

**Comment by Munksgaard** [comment]
I can host us at the Fintech Lab :+1:

**Comment by ErikMejerHansen** [comment]
Fantastic @Munksgaard! I'll update the Meetup tomorrow.

**Comment by vanjacosic** [comment]
I was in Lisbon for ElixirConf and mostly offline till now, so forgot to plan this and book a venue. 
Thank you Philip for hosting!
Enjoy the family time Erik, we'll see you in May 🎂

**Comment by grych** [comment]
Hi guys. 
Sorry that I was not taking, but for our May event I will bring up my girlfriend. She is completely new in programming :)
