### ISSUE TITLE
Next Meetup and Summer plans

### ISSUE THREAD

**Issue by ErikMejerHansen** [cphex/cphex#76]
Hi Folks!

Hope you had a great meetup last week - super bummed that I missed it. 

I'd like to get the next meetup in the calendar. Do we go back to the 3rd Thursday in the month schedule? 
That would mean next meetup is: June 20th

I suggest we take a summer break in July and have the next-next meetup August 15th. 

How does that sound to folks?

**Comment by Munksgaard** [comment]
I think we should go back to our regular schedule, although it means that we cannot be here at the Fintech Lab (there is a summer party).

**Comment by ErikMejerHansen** [comment]
Time went by _fast_ (and things got very hectic on my end)!
Giving folks one week advance notice is probably not long enough.  I'll add a preliminary meetup one week later than usual - we can cancel again if that turns out to be a bad idea. 
The date would then be: June 27th

I can probably have something ready about building your own Livebook extensions. 

Anyone up for hosting?

/Erik

**Comment by Munksgaard** [comment]
Sounds like a good idea. Unfortunately I'll be on vacation so I won't be able to attend :-(

**Comment by vanjacosic** [comment]
Unfortunately I can't make it either, I have the Rust meetup that day 🦀 

Re. summer break: Makes sense. I was thinking of hosting a casual summer edition in July (probably 18th) to chat about v1.17 and types (hopefully with some sun?! 😩 ). 
But need to confirm a few things first.

**Comment by lehoff** [comment]
27th works for me.
Torben

**Comment by killerkiara** [comment]
27th works for me as well :) However my summer break still runs on the southern schedule, so I will miss both August and september meetups.

**Comment by ErikMejerHansen** [comment]
Meetup created: https://www.meetup.com/copenhagen-elixir-meetup/events/301712693/

@lehoff or @killerkiara are any of you able to host?

**Comment by killerkiara** [comment]
@ErikMejerHansen not this time unfortunately, as I will need to run off at some point to pick up a friend who is arriving. sorry :/

**Comment by ErikMejerHansen** [comment]
I think I've managed to figure out how to host at Maersk. Will update meetup on Monday.

**Comment by ErikMejerHansen** [comment]
[Meetup ](https://www.meetup.com/copenhagen-elixir-meetup/events/301712693/?slug=copenhagen-elixir-meetup&eventId=301712693) updated! 
🚨 Be aware that I've had to set a RSVP deadline
