### ISSUE TITLE
September Meetup

### ISSUE THREAD

**Issue by ErikMejerHansen** [cphex/cphex#78]
Hi Folks!

Do we want a September meetup?

I can provide shelter and snacks - but I don't have capacity to come up with at talk/workshop/anything. 

Anyone got something lined up? If not we'll reconvene in October, where I hope to have a Elixir+LEGO-robots workshop ready. 

Best, 
Erik

**Comment by Munksgaard** [comment]
I think it would be great to do something, but I also won't have time to plan anything. Perhaps we arrange a hacknight or something?

**Comment by Munksgaard** [comment]
I would greatly prefer if we could meet on a non-Thursday though :-)

**Comment by ErikMejerHansen** [comment]
@munksgaard: Whats your favourite day?
We can experiment with a different day - It's not like we've been pulling huge crowds on Thursdays (4 people last time) :)

**Comment by Munksgaard** [comment]
Pretty much any other day, but Wednesday would be fine. For instance, Wednesday 25/9?

**Comment by ErikMejerHansen** [comment]
Sounds like a plan! I'll get the Meetup created later today

**Comment by ErikMejerHansen** [comment]
Meetup up: https://www.meetup.com/copenhagen-elixir-meetup/events/303230008

**Comment by killerkiara** [comment]
Hello guys! I am (finally) back to the base and I can resume helping with organisation. I guess a meeting in September will not happen at this point. Maybe lets try and plan for October directly?

**Comment by killerkiara** [comment]
Ahhhh sorry, was too quick! I saw you planned one for tomorrow! I will not be able to join on Wednesdays until end of October. Enjoy tomorrow! See you next time hopefully!
