### ISSUE TITLE
October '24 Meetup

### ISSUE THREAD

**Issue by ErikMejerHansen** [cphex/cphex#79]
Hi folks! 

We had a pretty decent turnout for the September Meetup - Thanks to @Munksgaard for leading the session 🙏

I would suggest that we set the date for the October meetup at **Wednesday October 30th**. 

Anyone willing to host us? I can host again, but that means we'll have to leave at 19:00 instead of the usual 19:30 and I think that makes the meetup feel a bit short?

I have a suggestion for a workshop: "GenServers, Binaries and a LEGO Robot"
I've been playing with Web-bluetooth in Livebook and have it working pretty well. 

The idea goes something like this:
- I setup a Livebook and host it on Fly.io and everyone will be collaborating in it. 
- I connect a LEGO robot with for motors to the livebook from my machine
- We split into four teams - each team "owns" a motor
- We work trough an initial set of tasks - this will require building and parsing binaries:
    - Make the motor turn clockwise
    - Make the motor turn counter-clockwise
    - Make the motor stop
    - Make a simple motor command queue
  
- We work trough a set of collaborative tasks - this will require the teams to find a way of coordinating their processes:
    - Move the robot forwards/backwards  
    - Move the robot in different shapes:  Circles, Squares, etc

The outcome would be something along the lines of learning a bit about:
- Building and parsing binaries
- GenServers
- Coordinating processes

The thing is: I know that this can work on a technical level,  but I have _no_ idea if it would work as a fun workshop

**Comment by simonelnahas** [comment]
Sounds fun I will join. I don't have any venue at hand. But perhaps Copenhagen fintech could be used again @Munksgaard ?

**Comment by Munksgaard** [comment]
Lego robots sound amazing! I'll look forward to it!

I've made arrangements to host us here at the Fintech Lab again. I've booked the canteen (which is where we held the beginners' workshop), because I think that'll be better suited for a workshop than the Lounge (where we've also previously had meetups).

**Comment by ErikMejerHansen** [comment]
Thank you for hosting @Munksgaard !
I've published the event on Meetup.com: https://www.meetup.com/copenhagen-elixir-meetup/events/304004079

@Munksgaard Would you like me to set RSVP requirement or limit the number of attendees?
Is there any "How do you find us" into to add?

**Comment by Munksgaard** [comment]
> @Munksgaard Would you like me to set RSVP requirement or limit the number of attendees?

I've booked the canteen for us again, so it should be possible to host quite a few people. Let's put an upper limit of 25, just so we don't overwhelm ourselves.

> Is there any "How do you find us" into to add?

> Ground floor, straight ahead and turn right at the elevator.
> Call "Philip Munksgaard" under "LEAF" on the door-phone to get in if the door is closed.

**Comment by ErikMejerHansen** [comment]
Apologies for the late cancellation - I had really been looking forward to this one, but I have unfortunately taken ill.

**Comment by simonelnahas** [comment]
So the entire event is cancelled or you are just not joining @ErikMejerHansen ? 😊

**Comment by simonelnahas** [comment]
Yeah. Once you have recovered. Let's quickly get another one setup 😊

**Comment by killerkiara** [comment]
Hello everyone! I hope you are recovered and well again @ErikMejerHansen ! Do you guys think we could manage to do it next Wednesday (November 13th?)? I will be unfortunately be away again the last week of November :/
